// Code generated by github.com/actgardner/gogen-avro/v10. DO NOT EDIT.
/*
 * SOURCE:
 *     ListInterface245.avsc
 */
package HCMInterface245Events

import (
	"encoding/json"
	"fmt"
	"io"

	"github.com/actgardner/gogen-avro/v10/compiler"
	"github.com/actgardner/gogen-avro/v10/vm"
	"github.com/actgardner/gogen-avro/v10/vm/types"
)

var _ = fmt.Printf

type Interface245Data struct {
	Legajo string `json:"Legajo"`

	Concepto string `json:"Concepto"`

	Monto string `json:"Monto"`

	FechaDesde string `json:"FechaDesde"`

	FechaHasta string `json:"FechaHasta"`
}

const Interface245DataAvroCRC64Fingerprint = "IJl\xe8'\xad'd"

func NewInterface245Data() Interface245Data {
	r := Interface245Data{}
	return r
}

func DeserializeInterface245Data(r io.Reader) (Interface245Data, error) {
	t := NewInterface245Data()
	deser, err := compiler.CompileSchemaBytes([]byte(t.Schema()), []byte(t.Schema()))
	if err != nil {
		return t, err
	}

	err = vm.Eval(r, deser, &t)
	return t, err
}

func DeserializeInterface245DataFromSchema(r io.Reader, schema string) (Interface245Data, error) {
	t := NewInterface245Data()

	deser, err := compiler.CompileSchemaBytes([]byte(schema), []byte(t.Schema()))
	if err != nil {
		return t, err
	}

	err = vm.Eval(r, deser, &t)
	return t, err
}

func writeInterface245Data(r Interface245Data, w io.Writer) error {
	var err error
	err = vm.WriteString(r.Legajo, w)
	if err != nil {
		return err
	}
	err = vm.WriteString(r.Concepto, w)
	if err != nil {
		return err
	}
	err = vm.WriteString(r.Monto, w)
	if err != nil {
		return err
	}
	err = vm.WriteString(r.FechaDesde, w)
	if err != nil {
		return err
	}
	err = vm.WriteString(r.FechaHasta, w)
	if err != nil {
		return err
	}
	return err
}

func (r Interface245Data) Serialize(w io.Writer) error {
	return writeInterface245Data(r, w)
}

func (r Interface245Data) Schema() string {
	return "{\"fields\":[{\"name\":\"Legajo\",\"type\":\"string\"},{\"name\":\"Concepto\",\"type\":\"string\"},{\"name\":\"Monto\",\"type\":\"string\"},{\"name\":\"FechaDesde\",\"type\":\"string\"},{\"name\":\"FechaHasta\",\"type\":\"string\"}],\"name\":\"Andreani.HCMInterface245.Events.Record.Interface245Data\",\"type\":\"record\"}"
}

func (r Interface245Data) SchemaName() string {
	return "Andreani.HCMInterface245.Events.Record.Interface245Data"
}

func (_ Interface245Data) SetBoolean(v bool)    { panic("Unsupported operation") }
func (_ Interface245Data) SetInt(v int32)       { panic("Unsupported operation") }
func (_ Interface245Data) SetLong(v int64)      { panic("Unsupported operation") }
func (_ Interface245Data) SetFloat(v float32)   { panic("Unsupported operation") }
func (_ Interface245Data) SetDouble(v float64)  { panic("Unsupported operation") }
func (_ Interface245Data) SetBytes(v []byte)    { panic("Unsupported operation") }
func (_ Interface245Data) SetString(v string)   { panic("Unsupported operation") }
func (_ Interface245Data) SetUnionElem(v int64) { panic("Unsupported operation") }

func (r *Interface245Data) Get(i int) types.Field {
	switch i {
	case 0:
		w := types.String{Target: &r.Legajo}

		return w

	case 1:
		w := types.String{Target: &r.Concepto}

		return w

	case 2:
		w := types.String{Target: &r.Monto}

		return w

	case 3:
		w := types.String{Target: &r.FechaDesde}

		return w

	case 4:
		w := types.String{Target: &r.FechaHasta}

		return w

	}
	panic("Unknown field index")
}

func (r *Interface245Data) SetDefault(i int) {
	switch i {
	}
	panic("Unknown field index")
}

func (r *Interface245Data) NullField(i int) {
	switch i {
	}
	panic("Not a nullable field index")
}

func (_ Interface245Data) AppendMap(key string) types.Field { panic("Unsupported operation") }
func (_ Interface245Data) AppendArray() types.Field         { panic("Unsupported operation") }
func (_ Interface245Data) HintSize(int)                     { panic("Unsupported operation") }
func (_ Interface245Data) Finalize()                        {}

func (_ Interface245Data) AvroCRC64Fingerprint() []byte {
	return []byte(Interface245DataAvroCRC64Fingerprint)
}

func (r Interface245Data) MarshalJSON() ([]byte, error) {
	var err error
	output := make(map[string]json.RawMessage)
	output["Legajo"], err = json.Marshal(r.Legajo)
	if err != nil {
		return nil, err
	}
	output["Concepto"], err = json.Marshal(r.Concepto)
	if err != nil {
		return nil, err
	}
	output["Monto"], err = json.Marshal(r.Monto)
	if err != nil {
		return nil, err
	}
	output["FechaDesde"], err = json.Marshal(r.FechaDesde)
	if err != nil {
		return nil, err
	}
	output["FechaHasta"], err = json.Marshal(r.FechaHasta)
	if err != nil {
		return nil, err
	}
	return json.Marshal(output)
}

func (r *Interface245Data) UnmarshalJSON(data []byte) error {
	var fields map[string]json.RawMessage
	if err := json.Unmarshal(data, &fields); err != nil {
		return err
	}

	var val json.RawMessage
	val = func() json.RawMessage {
		if v, ok := fields["Legajo"]; ok {
			return v
		}
		return nil
	}()

	if val != nil {
		if err := json.Unmarshal([]byte(val), &r.Legajo); err != nil {
			return err
		}
	} else {
		return fmt.Errorf("no value specified for Legajo")
	}
	val = func() json.RawMessage {
		if v, ok := fields["Concepto"]; ok {
			return v
		}
		return nil
	}()

	if val != nil {
		if err := json.Unmarshal([]byte(val), &r.Concepto); err != nil {
			return err
		}
	} else {
		return fmt.Errorf("no value specified for Concepto")
	}
	val = func() json.RawMessage {
		if v, ok := fields["Monto"]; ok {
			return v
		}
		return nil
	}()

	if val != nil {
		if err := json.Unmarshal([]byte(val), &r.Monto); err != nil {
			return err
		}
	} else {
		return fmt.Errorf("no value specified for Monto")
	}
	val = func() json.RawMessage {
		if v, ok := fields["FechaDesde"]; ok {
			return v
		}
		return nil
	}()

	if val != nil {
		if err := json.Unmarshal([]byte(val), &r.FechaDesde); err != nil {
			return err
		}
	} else {
		return fmt.Errorf("no value specified for FechaDesde")
	}
	val = func() json.RawMessage {
		if v, ok := fields["FechaHasta"]; ok {
			return v
		}
		return nil
	}()

	if val != nil {
		if err := json.Unmarshal([]byte(val), &r.FechaHasta); err != nil {
			return err
		}
	} else {
		return fmt.Errorf("no value specified for FechaHasta")
	}
	return nil
}
