// Code generated by github.com/actgardner/gogen-avro/v10. DO NOT EDIT.
/*
 * SOURCE:
 *     Evento.avsc
 */
package APIPuntosDeTerceroEvents

import (
	"encoding/json"
	"fmt"
	"io"

	"github.com/actgardner/gogen-avro/v10/compiler"
	"github.com/actgardner/gogen-avro/v10/vm"
	"github.com/actgardner/gogen-avro/v10/vm/types"
)

type UnionNullPuntoDeTerceroTypeEnum int

const (
	UnionNullPuntoDeTerceroTypeEnumPuntoDeTercero UnionNullPuntoDeTerceroTypeEnum = 1
)

type UnionNullPuntoDeTercero struct {
	Null           *types.NullVal
	PuntoDeTercero PuntoDeTercero
	UnionType      UnionNullPuntoDeTerceroTypeEnum
}

func writeUnionNullPuntoDeTercero(r *UnionNullPuntoDeTercero, w io.Writer) error {

	if r == nil {
		err := vm.WriteLong(0, w)
		return err
	}

	err := vm.WriteLong(int64(r.UnionType), w)
	if err != nil {
		return err
	}
	switch r.UnionType {
	case UnionNullPuntoDeTerceroTypeEnumPuntoDeTercero:
		return writePuntoDeTercero(r.PuntoDeTercero, w)
	}
	return fmt.Errorf("invalid value for *UnionNullPuntoDeTercero")
}

func NewUnionNullPuntoDeTercero() *UnionNullPuntoDeTercero {
	return &UnionNullPuntoDeTercero{}
}

func (r *UnionNullPuntoDeTercero) Serialize(w io.Writer) error {
	return writeUnionNullPuntoDeTercero(r, w)
}

func DeserializeUnionNullPuntoDeTercero(r io.Reader) (*UnionNullPuntoDeTercero, error) {
	t := NewUnionNullPuntoDeTercero()
	deser, err := compiler.CompileSchemaBytes([]byte(t.Schema()), []byte(t.Schema()))
	if err != nil {
		return t, err
	}

	err = vm.Eval(r, deser, t)

	if err != nil {
		return t, err
	}
	return t, err
}

func DeserializeUnionNullPuntoDeTerceroFromSchema(r io.Reader, schema string) (*UnionNullPuntoDeTercero, error) {
	t := NewUnionNullPuntoDeTercero()
	deser, err := compiler.CompileSchemaBytes([]byte(schema), []byte(t.Schema()))
	if err != nil {
		return t, err
	}

	err = vm.Eval(r, deser, t)

	if err != nil {
		return t, err
	}
	return t, err
}

func (r *UnionNullPuntoDeTercero) Schema() string {
	return "[\"null\",{\"fields\":[{\"name\":\"id\",\"type\":[\"null\",\"int\"]},{\"name\":\"nombre\",\"type\":\"string\"},{\"name\":\"telefono\",\"type\":[\"null\",\"string\"]},{\"name\":\"horarioDeAtencion\",\"type\":\"string\"},{\"name\":\"observaciones\",\"type\":[\"null\",\"string\"]},{\"name\":\"admiteEnvios\",\"type\":[\"null\",\"int\"]},{\"name\":\"entregaEnvios\",\"type\":[\"null\",\"int\"]},{\"name\":\"tipo\",\"type\":\"string\"},{\"name\":\"referencia\",\"type\":[\"null\",\"string\"]},{\"name\":\"responsable\",\"type\":[\"null\",{\"fields\":[{\"name\":\"nombre\",\"type\":\"string\"},{\"name\":\"apellido\",\"type\":[\"null\",\"string\"]},{\"name\":\"mail\",\"type\":\"string\"}],\"name\":\"Responsable\",\"type\":\"record\"}]},{\"name\":\"ubicacion\",\"type\":[\"null\",{\"fields\":[{\"name\":\"calle\",\"type\":\"string\"},{\"name\":\"numero\",\"type\":[\"null\",\"string\"]},{\"name\":\"piso\",\"type\":[\"null\",\"string\"]},{\"name\":\"departamento\",\"type\":[\"null\",\"string\"]},{\"name\":\"codigoPostal\",\"type\":\"string\"},{\"name\":\"latitud\",\"type\":\"string\"},{\"name\":\"longitud\",\"type\":\"string\"},{\"name\":\"region\",\"type\":[\"null\",\"string\"]}],\"name\":\"Ubicacion\",\"type\":\"record\"}]},{\"name\":\"activo\",\"type\":[\"null\",\"boolean\"]}],\"name\":\"PuntoDeTercero\",\"namespace\":\"Andreani.PuntoDeTercero.Events.Common\",\"type\":\"record\"}]"
}

func (_ *UnionNullPuntoDeTercero) SetBoolean(v bool)   { panic("Unsupported operation") }
func (_ *UnionNullPuntoDeTercero) SetInt(v int32)      { panic("Unsupported operation") }
func (_ *UnionNullPuntoDeTercero) SetFloat(v float32)  { panic("Unsupported operation") }
func (_ *UnionNullPuntoDeTercero) SetDouble(v float64) { panic("Unsupported operation") }
func (_ *UnionNullPuntoDeTercero) SetBytes(v []byte)   { panic("Unsupported operation") }
func (_ *UnionNullPuntoDeTercero) SetString(v string)  { panic("Unsupported operation") }

func (r *UnionNullPuntoDeTercero) SetLong(v int64) {

	r.UnionType = (UnionNullPuntoDeTerceroTypeEnum)(v)
}

func (r *UnionNullPuntoDeTercero) Get(i int) types.Field {

	switch i {
	case 0:
		return r.Null
	case 1:
		r.PuntoDeTercero = NewPuntoDeTercero()
		return &types.Record{Target: (&r.PuntoDeTercero)}
	}
	panic("Unknown field index")
}
func (_ *UnionNullPuntoDeTercero) NullField(i int)                  { panic("Unsupported operation") }
func (_ *UnionNullPuntoDeTercero) HintSize(i int)                   { panic("Unsupported operation") }
func (_ *UnionNullPuntoDeTercero) SetDefault(i int)                 { panic("Unsupported operation") }
func (_ *UnionNullPuntoDeTercero) AppendMap(key string) types.Field { panic("Unsupported operation") }
func (_ *UnionNullPuntoDeTercero) AppendArray() types.Field         { panic("Unsupported operation") }
func (_ *UnionNullPuntoDeTercero) Finalize()                        {}

func (r *UnionNullPuntoDeTercero) MarshalJSON() ([]byte, error) {

	if r == nil {
		return []byte("null"), nil
	}

	switch r.UnionType {
	case UnionNullPuntoDeTerceroTypeEnumPuntoDeTercero:
		return json.Marshal(map[string]interface{}{"Andreani.PuntoDeTercero.Events.Common.PuntoDeTercero": r.PuntoDeTercero})
	}
	return nil, fmt.Errorf("invalid value for *UnionNullPuntoDeTercero")
}

func (r *UnionNullPuntoDeTercero) UnmarshalJSON(data []byte) error {

	var fields map[string]json.RawMessage
	if err := json.Unmarshal(data, &fields); err != nil {
		return err
	}
	if len(fields) > 1 {
		return fmt.Errorf("more than one type supplied for union")
	}
	if value, ok := fields["Andreani.PuntoDeTercero.Events.Common.PuntoDeTercero"]; ok {
		r.UnionType = 1
		return json.Unmarshal([]byte(value), &r.PuntoDeTercero)
	}
	return fmt.Errorf("invalid value for *UnionNullPuntoDeTercero")
}
