// Code generated by github.com/actgardner/gogen-avro/v10. DO NOT EDIT.
/*
 * SOURCE:
 *     ListInterface2024.avsc
 */
package HCMInterface2024Events

import (
	"encoding/json"
	"fmt"
	"io"

	"github.com/actgardner/gogen-avro/v10/compiler"
	"github.com/actgardner/gogen-avro/v10/vm"
	"github.com/actgardner/gogen-avro/v10/vm/types"
)

var _ = fmt.Printf

type Interface2024Data struct {
	Legajo string `json:"Legajo"`

	TipoAusencia string `json:"TipoAusencia"`

	SubTipo string `json:"SubTipo"`

	FechaDesde string `json:"FechaDesde"`

	FechaHasta string `json:"FechaHasta"`

	DiaCompleto string `json:"DiaCompleto"`

	HoraDesde string `json:"HoraDesde"`

	HoraHasta string `json:"HoraHasta"`

	CantidadHoras string `json:"CantidadHoras"`

	DiasHabiles string `json:"DiasHabiles"`

	DiasFeriados string `json:"DiasFeriados"`

	Estado string `json:"Estado"`

	Observaciones string `json:"Observaciones"`

	NroCertificado string `json:"NroCertificado"`

	FechaCertificado string `json:"FechaCertificado"`
}

const Interface2024DataAvroCRC64Fingerprint = "\x8b\x87`\xf2Y\x1aj&"

func NewInterface2024Data() Interface2024Data {
	r := Interface2024Data{}
	return r
}

func DeserializeInterface2024Data(r io.Reader) (Interface2024Data, error) {
	t := NewInterface2024Data()
	deser, err := compiler.CompileSchemaBytes([]byte(t.Schema()), []byte(t.Schema()))
	if err != nil {
		return t, err
	}

	err = vm.Eval(r, deser, &t)
	return t, err
}

func DeserializeInterface2024DataFromSchema(r io.Reader, schema string) (Interface2024Data, error) {
	t := NewInterface2024Data()

	deser, err := compiler.CompileSchemaBytes([]byte(schema), []byte(t.Schema()))
	if err != nil {
		return t, err
	}

	err = vm.Eval(r, deser, &t)
	return t, err
}

func writeInterface2024Data(r Interface2024Data, w io.Writer) error {
	var err error
	err = vm.WriteString(r.Legajo, w)
	if err != nil {
		return err
	}
	err = vm.WriteString(r.TipoAusencia, w)
	if err != nil {
		return err
	}
	err = vm.WriteString(r.SubTipo, w)
	if err != nil {
		return err
	}
	err = vm.WriteString(r.FechaDesde, w)
	if err != nil {
		return err
	}
	err = vm.WriteString(r.FechaHasta, w)
	if err != nil {
		return err
	}
	err = vm.WriteString(r.DiaCompleto, w)
	if err != nil {
		return err
	}
	err = vm.WriteString(r.HoraDesde, w)
	if err != nil {
		return err
	}
	err = vm.WriteString(r.HoraHasta, w)
	if err != nil {
		return err
	}
	err = vm.WriteString(r.CantidadHoras, w)
	if err != nil {
		return err
	}
	err = vm.WriteString(r.DiasHabiles, w)
	if err != nil {
		return err
	}
	err = vm.WriteString(r.DiasFeriados, w)
	if err != nil {
		return err
	}
	err = vm.WriteString(r.Estado, w)
	if err != nil {
		return err
	}
	err = vm.WriteString(r.Observaciones, w)
	if err != nil {
		return err
	}
	err = vm.WriteString(r.NroCertificado, w)
	if err != nil {
		return err
	}
	err = vm.WriteString(r.FechaCertificado, w)
	if err != nil {
		return err
	}
	return err
}

func (r Interface2024Data) Serialize(w io.Writer) error {
	return writeInterface2024Data(r, w)
}

func (r Interface2024Data) Schema() string {
	return "{\"fields\":[{\"name\":\"Legajo\",\"type\":\"string\"},{\"name\":\"TipoAusencia\",\"type\":\"string\"},{\"name\":\"SubTipo\",\"type\":\"string\"},{\"name\":\"FechaDesde\",\"type\":\"string\"},{\"name\":\"FechaHasta\",\"type\":\"string\"},{\"name\":\"DiaCompleto\",\"type\":\"string\"},{\"name\":\"HoraDesde\",\"type\":\"string\"},{\"name\":\"HoraHasta\",\"type\":\"string\"},{\"name\":\"CantidadHoras\",\"type\":\"string\"},{\"name\":\"DiasHabiles\",\"type\":\"string\"},{\"name\":\"DiasFeriados\",\"type\":\"string\"},{\"name\":\"Estado\",\"type\":\"string\"},{\"name\":\"Observaciones\",\"type\":\"string\"},{\"name\":\"NroCertificado\",\"type\":\"string\"},{\"name\":\"FechaCertificado\",\"type\":\"string\"}],\"name\":\"Andreani.HCMInterface2024.Events.Record.Interface2024Data\",\"type\":\"record\"}"
}

func (r Interface2024Data) SchemaName() string {
	return "Andreani.HCMInterface2024.Events.Record.Interface2024Data"
}

func (_ Interface2024Data) SetBoolean(v bool)    { panic("Unsupported operation") }
func (_ Interface2024Data) SetInt(v int32)       { panic("Unsupported operation") }
func (_ Interface2024Data) SetLong(v int64)      { panic("Unsupported operation") }
func (_ Interface2024Data) SetFloat(v float32)   { panic("Unsupported operation") }
func (_ Interface2024Data) SetDouble(v float64)  { panic("Unsupported operation") }
func (_ Interface2024Data) SetBytes(v []byte)    { panic("Unsupported operation") }
func (_ Interface2024Data) SetString(v string)   { panic("Unsupported operation") }
func (_ Interface2024Data) SetUnionElem(v int64) { panic("Unsupported operation") }

func (r *Interface2024Data) Get(i int) types.Field {
	switch i {
	case 0:
		w := types.String{Target: &r.Legajo}

		return w

	case 1:
		w := types.String{Target: &r.TipoAusencia}

		return w

	case 2:
		w := types.String{Target: &r.SubTipo}

		return w

	case 3:
		w := types.String{Target: &r.FechaDesde}

		return w

	case 4:
		w := types.String{Target: &r.FechaHasta}

		return w

	case 5:
		w := types.String{Target: &r.DiaCompleto}

		return w

	case 6:
		w := types.String{Target: &r.HoraDesde}

		return w

	case 7:
		w := types.String{Target: &r.HoraHasta}

		return w

	case 8:
		w := types.String{Target: &r.CantidadHoras}

		return w

	case 9:
		w := types.String{Target: &r.DiasHabiles}

		return w

	case 10:
		w := types.String{Target: &r.DiasFeriados}

		return w

	case 11:
		w := types.String{Target: &r.Estado}

		return w

	case 12:
		w := types.String{Target: &r.Observaciones}

		return w

	case 13:
		w := types.String{Target: &r.NroCertificado}

		return w

	case 14:
		w := types.String{Target: &r.FechaCertificado}

		return w

	}
	panic("Unknown field index")
}

func (r *Interface2024Data) SetDefault(i int) {
	switch i {
	}
	panic("Unknown field index")
}

func (r *Interface2024Data) NullField(i int) {
	switch i {
	}
	panic("Not a nullable field index")
}

func (_ Interface2024Data) AppendMap(key string) types.Field { panic("Unsupported operation") }
func (_ Interface2024Data) AppendArray() types.Field         { panic("Unsupported operation") }
func (_ Interface2024Data) HintSize(int)                     { panic("Unsupported operation") }
func (_ Interface2024Data) Finalize()                        {}

func (_ Interface2024Data) AvroCRC64Fingerprint() []byte {
	return []byte(Interface2024DataAvroCRC64Fingerprint)
}

func (r Interface2024Data) MarshalJSON() ([]byte, error) {
	var err error
	output := make(map[string]json.RawMessage)
	output["Legajo"], err = json.Marshal(r.Legajo)
	if err != nil {
		return nil, err
	}
	output["TipoAusencia"], err = json.Marshal(r.TipoAusencia)
	if err != nil {
		return nil, err
	}
	output["SubTipo"], err = json.Marshal(r.SubTipo)
	if err != nil {
		return nil, err
	}
	output["FechaDesde"], err = json.Marshal(r.FechaDesde)
	if err != nil {
		return nil, err
	}
	output["FechaHasta"], err = json.Marshal(r.FechaHasta)
	if err != nil {
		return nil, err
	}
	output["DiaCompleto"], err = json.Marshal(r.DiaCompleto)
	if err != nil {
		return nil, err
	}
	output["HoraDesde"], err = json.Marshal(r.HoraDesde)
	if err != nil {
		return nil, err
	}
	output["HoraHasta"], err = json.Marshal(r.HoraHasta)
	if err != nil {
		return nil, err
	}
	output["CantidadHoras"], err = json.Marshal(r.CantidadHoras)
	if err != nil {
		return nil, err
	}
	output["DiasHabiles"], err = json.Marshal(r.DiasHabiles)
	if err != nil {
		return nil, err
	}
	output["DiasFeriados"], err = json.Marshal(r.DiasFeriados)
	if err != nil {
		return nil, err
	}
	output["Estado"], err = json.Marshal(r.Estado)
	if err != nil {
		return nil, err
	}
	output["Observaciones"], err = json.Marshal(r.Observaciones)
	if err != nil {
		return nil, err
	}
	output["NroCertificado"], err = json.Marshal(r.NroCertificado)
	if err != nil {
		return nil, err
	}
	output["FechaCertificado"], err = json.Marshal(r.FechaCertificado)
	if err != nil {
		return nil, err
	}
	return json.Marshal(output)
}

func (r *Interface2024Data) UnmarshalJSON(data []byte) error {
	var fields map[string]json.RawMessage
	if err := json.Unmarshal(data, &fields); err != nil {
		return err
	}

	var val json.RawMessage
	val = func() json.RawMessage {
		if v, ok := fields["Legajo"]; ok {
			return v
		}
		return nil
	}()

	if val != nil {
		if err := json.Unmarshal([]byte(val), &r.Legajo); err != nil {
			return err
		}
	} else {
		return fmt.Errorf("no value specified for Legajo")
	}
	val = func() json.RawMessage {
		if v, ok := fields["TipoAusencia"]; ok {
			return v
		}
		return nil
	}()

	if val != nil {
		if err := json.Unmarshal([]byte(val), &r.TipoAusencia); err != nil {
			return err
		}
	} else {
		return fmt.Errorf("no value specified for TipoAusencia")
	}
	val = func() json.RawMessage {
		if v, ok := fields["SubTipo"]; ok {
			return v
		}
		return nil
	}()

	if val != nil {
		if err := json.Unmarshal([]byte(val), &r.SubTipo); err != nil {
			return err
		}
	} else {
		return fmt.Errorf("no value specified for SubTipo")
	}
	val = func() json.RawMessage {
		if v, ok := fields["FechaDesde"]; ok {
			return v
		}
		return nil
	}()

	if val != nil {
		if err := json.Unmarshal([]byte(val), &r.FechaDesde); err != nil {
			return err
		}
	} else {
		return fmt.Errorf("no value specified for FechaDesde")
	}
	val = func() json.RawMessage {
		if v, ok := fields["FechaHasta"]; ok {
			return v
		}
		return nil
	}()

	if val != nil {
		if err := json.Unmarshal([]byte(val), &r.FechaHasta); err != nil {
			return err
		}
	} else {
		return fmt.Errorf("no value specified for FechaHasta")
	}
	val = func() json.RawMessage {
		if v, ok := fields["DiaCompleto"]; ok {
			return v
		}
		return nil
	}()

	if val != nil {
		if err := json.Unmarshal([]byte(val), &r.DiaCompleto); err != nil {
			return err
		}
	} else {
		return fmt.Errorf("no value specified for DiaCompleto")
	}
	val = func() json.RawMessage {
		if v, ok := fields["HoraDesde"]; ok {
			return v
		}
		return nil
	}()

	if val != nil {
		if err := json.Unmarshal([]byte(val), &r.HoraDesde); err != nil {
			return err
		}
	} else {
		return fmt.Errorf("no value specified for HoraDesde")
	}
	val = func() json.RawMessage {
		if v, ok := fields["HoraHasta"]; ok {
			return v
		}
		return nil
	}()

	if val != nil {
		if err := json.Unmarshal([]byte(val), &r.HoraHasta); err != nil {
			return err
		}
	} else {
		return fmt.Errorf("no value specified for HoraHasta")
	}
	val = func() json.RawMessage {
		if v, ok := fields["CantidadHoras"]; ok {
			return v
		}
		return nil
	}()

	if val != nil {
		if err := json.Unmarshal([]byte(val), &r.CantidadHoras); err != nil {
			return err
		}
	} else {
		return fmt.Errorf("no value specified for CantidadHoras")
	}
	val = func() json.RawMessage {
		if v, ok := fields["DiasHabiles"]; ok {
			return v
		}
		return nil
	}()

	if val != nil {
		if err := json.Unmarshal([]byte(val), &r.DiasHabiles); err != nil {
			return err
		}
	} else {
		return fmt.Errorf("no value specified for DiasHabiles")
	}
	val = func() json.RawMessage {
		if v, ok := fields["DiasFeriados"]; ok {
			return v
		}
		return nil
	}()

	if val != nil {
		if err := json.Unmarshal([]byte(val), &r.DiasFeriados); err != nil {
			return err
		}
	} else {
		return fmt.Errorf("no value specified for DiasFeriados")
	}
	val = func() json.RawMessage {
		if v, ok := fields["Estado"]; ok {
			return v
		}
		return nil
	}()

	if val != nil {
		if err := json.Unmarshal([]byte(val), &r.Estado); err != nil {
			return err
		}
	} else {
		return fmt.Errorf("no value specified for Estado")
	}
	val = func() json.RawMessage {
		if v, ok := fields["Observaciones"]; ok {
			return v
		}
		return nil
	}()

	if val != nil {
		if err := json.Unmarshal([]byte(val), &r.Observaciones); err != nil {
			return err
		}
	} else {
		return fmt.Errorf("no value specified for Observaciones")
	}
	val = func() json.RawMessage {
		if v, ok := fields["NroCertificado"]; ok {
			return v
		}
		return nil
	}()

	if val != nil {
		if err := json.Unmarshal([]byte(val), &r.NroCertificado); err != nil {
			return err
		}
	} else {
		return fmt.Errorf("no value specified for NroCertificado")
	}
	val = func() json.RawMessage {
		if v, ok := fields["FechaCertificado"]; ok {
			return v
		}
		return nil
	}()

	if val != nil {
		if err := json.Unmarshal([]byte(val), &r.FechaCertificado); err != nil {
			return err
		}
	} else {
		return fmt.Errorf("no value specified for FechaCertificado")
	}
	return nil
}
