// Code generated by github.com/actgardner/gogen-avro/v10. DO NOT EDIT.
/*
 * SOURCE:
 *     NotificacionesMKT.avsc
 */
package NotificacionesEvents

import (
	"encoding/json"
	"fmt"
	"io"

	"github.com/actgardner/gogen-avro/v10/compiler"
	"github.com/actgardner/gogen-avro/v10/vm"
	"github.com/actgardner/gogen-avro/v10/vm/types"
)

var _ = fmt.Printf

type NotificacionesMKT struct {
	IdModelo *UnionNullLong `json:"idModelo"`

	ClienteId *UnionNullString `json:"clienteId"`

	Destinatario *UnionNullString `json:"destinatario"`

	ClienteNombre *UnionNullString `json:"clienteNombre"`

	FechaNotificacion *UnionNullLong `json:"fechaNotificacion"`

	FechaEvento *UnionNullLong `json:"fechaEvento"`

	DestinatarioEstado *UnionNullString `json:"destinatarioEstado"`

	DestinatarioObservacion *UnionNullString `json:"destinatarioObservacion"`

	IdEvento *UnionNullInt `json:"idEvento"`

	IdRegla *UnionNullInt `json:"idRegla"`

	DestinatarioNotificacion *UnionNullString `json:"destinatarioNotificacion"`
}

const NotificacionesMKTAvroCRC64Fingerprint = "5\xd5x\x9c\xb5\x96ޟ"

func NewNotificacionesMKT() NotificacionesMKT {
	r := NotificacionesMKT{}
	r.IdModelo = nil
	r.ClienteId = nil
	r.Destinatario = nil
	r.ClienteNombre = nil
	r.FechaNotificacion = nil
	r.FechaEvento = nil
	r.DestinatarioEstado = nil
	r.DestinatarioObservacion = nil
	r.IdEvento = nil
	r.IdRegla = nil
	r.DestinatarioNotificacion = nil
	return r
}

func DeserializeNotificacionesMKT(r io.Reader) (NotificacionesMKT, error) {
	t := NewNotificacionesMKT()
	deser, err := compiler.CompileSchemaBytes([]byte(t.Schema()), []byte(t.Schema()))
	if err != nil {
		return t, err
	}

	err = vm.Eval(r, deser, &t)
	return t, err
}

func DeserializeNotificacionesMKTFromSchema(r io.Reader, schema string) (NotificacionesMKT, error) {
	t := NewNotificacionesMKT()

	deser, err := compiler.CompileSchemaBytes([]byte(schema), []byte(t.Schema()))
	if err != nil {
		return t, err
	}

	err = vm.Eval(r, deser, &t)
	return t, err
}

func writeNotificacionesMKT(r NotificacionesMKT, w io.Writer) error {
	var err error
	err = writeUnionNullLong(r.IdModelo, w)
	if err != nil {
		return err
	}
	err = writeUnionNullString(r.ClienteId, w)
	if err != nil {
		return err
	}
	err = writeUnionNullString(r.Destinatario, w)
	if err != nil {
		return err
	}
	err = writeUnionNullString(r.ClienteNombre, w)
	if err != nil {
		return err
	}
	err = writeUnionNullLong(r.FechaNotificacion, w)
	if err != nil {
		return err
	}
	err = writeUnionNullLong(r.FechaEvento, w)
	if err != nil {
		return err
	}
	err = writeUnionNullString(r.DestinatarioEstado, w)
	if err != nil {
		return err
	}
	err = writeUnionNullString(r.DestinatarioObservacion, w)
	if err != nil {
		return err
	}
	err = writeUnionNullInt(r.IdEvento, w)
	if err != nil {
		return err
	}
	err = writeUnionNullInt(r.IdRegla, w)
	if err != nil {
		return err
	}
	err = writeUnionNullString(r.DestinatarioNotificacion, w)
	if err != nil {
		return err
	}
	return err
}

func (r NotificacionesMKT) Serialize(w io.Writer) error {
	return writeNotificacionesMKT(r, w)
}

func (r NotificacionesMKT) Schema() string {
	return "{\"fields\":[{\"default\":null,\"name\":\"idModelo\",\"type\":[\"null\",\"long\"]},{\"default\":null,\"name\":\"clienteId\",\"type\":[\"null\",\"string\"]},{\"default\":null,\"name\":\"destinatario\",\"type\":[\"null\",\"string\"]},{\"default\":null,\"name\":\"clienteNombre\",\"type\":[\"null\",\"string\"]},{\"default\":null,\"name\":\"fechaNotificacion\",\"type\":[\"null\",{\"logicalType\":\"timestamp-millis\",\"type\":\"long\"}]},{\"default\":null,\"name\":\"fechaEvento\",\"type\":[\"null\",{\"logicalType\":\"timestamp-millis\",\"type\":\"long\"}]},{\"default\":null,\"name\":\"destinatarioEstado\",\"type\":[\"null\",\"string\"]},{\"default\":null,\"name\":\"destinatarioObservacion\",\"type\":[\"null\",\"string\"]},{\"default\":null,\"name\":\"idEvento\",\"type\":[\"null\",\"int\"]},{\"default\":null,\"name\":\"idRegla\",\"type\":[\"null\",\"int\"]},{\"default\":null,\"name\":\"destinatarioNotificacion\",\"type\":[\"null\",\"string\"]}],\"name\":\"Andreani.Notificaciones.Events.Records.NotificacionesMKT\",\"type\":\"record\"}"
}

func (r NotificacionesMKT) SchemaName() string {
	return "Andreani.Notificaciones.Events.Records.NotificacionesMKT"
}

func (_ NotificacionesMKT) SetBoolean(v bool)    { panic("Unsupported operation") }
func (_ NotificacionesMKT) SetInt(v int32)       { panic("Unsupported operation") }
func (_ NotificacionesMKT) SetLong(v int64)      { panic("Unsupported operation") }
func (_ NotificacionesMKT) SetFloat(v float32)   { panic("Unsupported operation") }
func (_ NotificacionesMKT) SetDouble(v float64)  { panic("Unsupported operation") }
func (_ NotificacionesMKT) SetBytes(v []byte)    { panic("Unsupported operation") }
func (_ NotificacionesMKT) SetString(v string)   { panic("Unsupported operation") }
func (_ NotificacionesMKT) SetUnionElem(v int64) { panic("Unsupported operation") }

func (r *NotificacionesMKT) Get(i int) types.Field {
	switch i {
	case 0:
		r.IdModelo = NewUnionNullLong()

		return r.IdModelo
	case 1:
		r.ClienteId = NewUnionNullString()

		return r.ClienteId
	case 2:
		r.Destinatario = NewUnionNullString()

		return r.Destinatario
	case 3:
		r.ClienteNombre = NewUnionNullString()

		return r.ClienteNombre
	case 4:
		r.FechaNotificacion = NewUnionNullLong()

		return r.FechaNotificacion
	case 5:
		r.FechaEvento = NewUnionNullLong()

		return r.FechaEvento
	case 6:
		r.DestinatarioEstado = NewUnionNullString()

		return r.DestinatarioEstado
	case 7:
		r.DestinatarioObservacion = NewUnionNullString()

		return r.DestinatarioObservacion
	case 8:
		r.IdEvento = NewUnionNullInt()

		return r.IdEvento
	case 9:
		r.IdRegla = NewUnionNullInt()

		return r.IdRegla
	case 10:
		r.DestinatarioNotificacion = NewUnionNullString()

		return r.DestinatarioNotificacion
	}
	panic("Unknown field index")
}

func (r *NotificacionesMKT) SetDefault(i int) {
	switch i {
	case 0:
		r.IdModelo = nil
		return
	case 1:
		r.ClienteId = nil
		return
	case 2:
		r.Destinatario = nil
		return
	case 3:
		r.ClienteNombre = nil
		return
	case 4:
		r.FechaNotificacion = nil
		return
	case 5:
		r.FechaEvento = nil
		return
	case 6:
		r.DestinatarioEstado = nil
		return
	case 7:
		r.DestinatarioObservacion = nil
		return
	case 8:
		r.IdEvento = nil
		return
	case 9:
		r.IdRegla = nil
		return
	case 10:
		r.DestinatarioNotificacion = nil
		return
	}
	panic("Unknown field index")
}

func (r *NotificacionesMKT) NullField(i int) {
	switch i {
	case 0:
		r.IdModelo = nil
		return
	case 1:
		r.ClienteId = nil
		return
	case 2:
		r.Destinatario = nil
		return
	case 3:
		r.ClienteNombre = nil
		return
	case 4:
		r.FechaNotificacion = nil
		return
	case 5:
		r.FechaEvento = nil
		return
	case 6:
		r.DestinatarioEstado = nil
		return
	case 7:
		r.DestinatarioObservacion = nil
		return
	case 8:
		r.IdEvento = nil
		return
	case 9:
		r.IdRegla = nil
		return
	case 10:
		r.DestinatarioNotificacion = nil
		return
	}
	panic("Not a nullable field index")
}

func (_ NotificacionesMKT) AppendMap(key string) types.Field { panic("Unsupported operation") }
func (_ NotificacionesMKT) AppendArray() types.Field         { panic("Unsupported operation") }
func (_ NotificacionesMKT) HintSize(int)                     { panic("Unsupported operation") }
func (_ NotificacionesMKT) Finalize()                        {}

func (_ NotificacionesMKT) AvroCRC64Fingerprint() []byte {
	return []byte(NotificacionesMKTAvroCRC64Fingerprint)
}

func (r NotificacionesMKT) MarshalJSON() ([]byte, error) {
	var err error
	output := make(map[string]json.RawMessage)
	output["idModelo"], err = json.Marshal(r.IdModelo)
	if err != nil {
		return nil, err
	}
	output["clienteId"], err = json.Marshal(r.ClienteId)
	if err != nil {
		return nil, err
	}
	output["destinatario"], err = json.Marshal(r.Destinatario)
	if err != nil {
		return nil, err
	}
	output["clienteNombre"], err = json.Marshal(r.ClienteNombre)
	if err != nil {
		return nil, err
	}
	output["fechaNotificacion"], err = json.Marshal(r.FechaNotificacion)
	if err != nil {
		return nil, err
	}
	output["fechaEvento"], err = json.Marshal(r.FechaEvento)
	if err != nil {
		return nil, err
	}
	output["destinatarioEstado"], err = json.Marshal(r.DestinatarioEstado)
	if err != nil {
		return nil, err
	}
	output["destinatarioObservacion"], err = json.Marshal(r.DestinatarioObservacion)
	if err != nil {
		return nil, err
	}
	output["idEvento"], err = json.Marshal(r.IdEvento)
	if err != nil {
		return nil, err
	}
	output["idRegla"], err = json.Marshal(r.IdRegla)
	if err != nil {
		return nil, err
	}
	output["destinatarioNotificacion"], err = json.Marshal(r.DestinatarioNotificacion)
	if err != nil {
		return nil, err
	}
	return json.Marshal(output)
}

func (r *NotificacionesMKT) UnmarshalJSON(data []byte) error {
	var fields map[string]json.RawMessage
	if err := json.Unmarshal(data, &fields); err != nil {
		return err
	}

	var val json.RawMessage
	val = func() json.RawMessage {
		if v, ok := fields["idModelo"]; ok {
			return v
		}
		return nil
	}()

	if val != nil {
		if err := json.Unmarshal([]byte(val), &r.IdModelo); err != nil {
			return err
		}
	} else {
		r.IdModelo = NewUnionNullLong()

		r.IdModelo = nil
	}
	val = func() json.RawMessage {
		if v, ok := fields["clienteId"]; ok {
			return v
		}
		return nil
	}()

	if val != nil {
		if err := json.Unmarshal([]byte(val), &r.ClienteId); err != nil {
			return err
		}
	} else {
		r.ClienteId = NewUnionNullString()

		r.ClienteId = nil
	}
	val = func() json.RawMessage {
		if v, ok := fields["destinatario"]; ok {
			return v
		}
		return nil
	}()

	if val != nil {
		if err := json.Unmarshal([]byte(val), &r.Destinatario); err != nil {
			return err
		}
	} else {
		r.Destinatario = NewUnionNullString()

		r.Destinatario = nil
	}
	val = func() json.RawMessage {
		if v, ok := fields["clienteNombre"]; ok {
			return v
		}
		return nil
	}()

	if val != nil {
		if err := json.Unmarshal([]byte(val), &r.ClienteNombre); err != nil {
			return err
		}
	} else {
		r.ClienteNombre = NewUnionNullString()

		r.ClienteNombre = nil
	}
	val = func() json.RawMessage {
		if v, ok := fields["fechaNotificacion"]; ok {
			return v
		}
		return nil
	}()

	if val != nil {
		if err := json.Unmarshal([]byte(val), &r.FechaNotificacion); err != nil {
			return err
		}
	} else {
		r.FechaNotificacion = NewUnionNullLong()

		r.FechaNotificacion = nil
	}
	val = func() json.RawMessage {
		if v, ok := fields["fechaEvento"]; ok {
			return v
		}
		return nil
	}()

	if val != nil {
		if err := json.Unmarshal([]byte(val), &r.FechaEvento); err != nil {
			return err
		}
	} else {
		r.FechaEvento = NewUnionNullLong()

		r.FechaEvento = nil
	}
	val = func() json.RawMessage {
		if v, ok := fields["destinatarioEstado"]; ok {
			return v
		}
		return nil
	}()

	if val != nil {
		if err := json.Unmarshal([]byte(val), &r.DestinatarioEstado); err != nil {
			return err
		}
	} else {
		r.DestinatarioEstado = NewUnionNullString()

		r.DestinatarioEstado = nil
	}
	val = func() json.RawMessage {
		if v, ok := fields["destinatarioObservacion"]; ok {
			return v
		}
		return nil
	}()

	if val != nil {
		if err := json.Unmarshal([]byte(val), &r.DestinatarioObservacion); err != nil {
			return err
		}
	} else {
		r.DestinatarioObservacion = NewUnionNullString()

		r.DestinatarioObservacion = nil
	}
	val = func() json.RawMessage {
		if v, ok := fields["idEvento"]; ok {
			return v
		}
		return nil
	}()

	if val != nil {
		if err := json.Unmarshal([]byte(val), &r.IdEvento); err != nil {
			return err
		}
	} else {
		r.IdEvento = NewUnionNullInt()

		r.IdEvento = nil
	}
	val = func() json.RawMessage {
		if v, ok := fields["idRegla"]; ok {
			return v
		}
		return nil
	}()

	if val != nil {
		if err := json.Unmarshal([]byte(val), &r.IdRegla); err != nil {
			return err
		}
	} else {
		r.IdRegla = NewUnionNullInt()

		r.IdRegla = nil
	}
	val = func() json.RawMessage {
		if v, ok := fields["destinatarioNotificacion"]; ok {
			return v
		}
		return nil
	}()

	if val != nil {
		if err := json.Unmarshal([]byte(val), &r.DestinatarioNotificacion); err != nil {
			return err
		}
	} else {
		r.DestinatarioNotificacion = NewUnionNullString()

		r.DestinatarioNotificacion = nil
	}
	return nil
}
