// Code generated by github.com/actgardner/gogen-avro/v10. DO NOT EDIT.
/*
 * SOURCE:
 *     PendienteDePago.avsc
 */
package NotificacionesEvents

import (
	"encoding/json"
	"fmt"
	"io"

	"github.com/actgardner/gogen-avro/v10/compiler"
	"github.com/actgardner/gogen-avro/v10/vm"
	"github.com/actgardner/gogen-avro/v10/vm/types"
)

var _ = fmt.Printf

type PendienteDePago struct {
	UsuarioId *UnionNullString `json:"usuarioId"`

	Email *UnionNullString `json:"email"`

	Nombre *UnionNullString `json:"nombre"`

	TelefonoCodigoArea *UnionNullString `json:"telefonoCodigoArea"`

	TelefonoNumero *UnionNullString `json:"telefonoNumero"`

	FechaModificacion *UnionNullString `json:"fechaModificacion"`

	Cupon *UnionNullString `json:"cupon"`

	CantidadDeEnvios *UnionNullInt `json:"cantidadDeEnvios"`

	DiasPendientes *UnionNullInt `json:"diasPendientes"`

	TipoDeServicio *UnionNullString `json:"tipoDeServicio"`

	Cuando *UnionNullLong `json:"cuando"`
}

const PendienteDePagoAvroCRC64Fingerprint = "\a\xb5\xdcw#\xa1\x01("

func NewPendienteDePago() PendienteDePago {
	r := PendienteDePago{}
	r.UsuarioId = nil
	r.Email = nil
	r.Nombre = nil
	r.TelefonoCodigoArea = nil
	r.TelefonoNumero = nil
	r.FechaModificacion = nil
	r.Cupon = nil
	r.CantidadDeEnvios = nil
	r.DiasPendientes = nil
	r.TipoDeServicio = nil
	r.Cuando = nil
	return r
}

func DeserializePendienteDePago(r io.Reader) (PendienteDePago, error) {
	t := NewPendienteDePago()
	deser, err := compiler.CompileSchemaBytes([]byte(t.Schema()), []byte(t.Schema()))
	if err != nil {
		return t, err
	}

	err = vm.Eval(r, deser, &t)
	return t, err
}

func DeserializePendienteDePagoFromSchema(r io.Reader, schema string) (PendienteDePago, error) {
	t := NewPendienteDePago()

	deser, err := compiler.CompileSchemaBytes([]byte(schema), []byte(t.Schema()))
	if err != nil {
		return t, err
	}

	err = vm.Eval(r, deser, &t)
	return t, err
}

func writePendienteDePago(r PendienteDePago, w io.Writer) error {
	var err error
	err = writeUnionNullString(r.UsuarioId, w)
	if err != nil {
		return err
	}
	err = writeUnionNullString(r.Email, w)
	if err != nil {
		return err
	}
	err = writeUnionNullString(r.Nombre, w)
	if err != nil {
		return err
	}
	err = writeUnionNullString(r.TelefonoCodigoArea, w)
	if err != nil {
		return err
	}
	err = writeUnionNullString(r.TelefonoNumero, w)
	if err != nil {
		return err
	}
	err = writeUnionNullString(r.FechaModificacion, w)
	if err != nil {
		return err
	}
	err = writeUnionNullString(r.Cupon, w)
	if err != nil {
		return err
	}
	err = writeUnionNullInt(r.CantidadDeEnvios, w)
	if err != nil {
		return err
	}
	err = writeUnionNullInt(r.DiasPendientes, w)
	if err != nil {
		return err
	}
	err = writeUnionNullString(r.TipoDeServicio, w)
	if err != nil {
		return err
	}
	err = writeUnionNullLong(r.Cuando, w)
	if err != nil {
		return err
	}
	return err
}

func (r PendienteDePago) Serialize(w io.Writer) error {
	return writePendienteDePago(r, w)
}

func (r PendienteDePago) Schema() string {
	return "{\"fields\":[{\"default\":null,\"name\":\"usuarioId\",\"type\":[\"null\",\"string\"]},{\"default\":null,\"name\":\"email\",\"type\":[\"null\",\"string\"]},{\"default\":null,\"name\":\"nombre\",\"type\":[\"null\",\"string\"]},{\"default\":null,\"name\":\"telefonoCodigoArea\",\"type\":[\"null\",\"string\"]},{\"default\":null,\"name\":\"telefonoNumero\",\"type\":[\"null\",\"string\"]},{\"default\":null,\"name\":\"fechaModificacion\",\"type\":[\"null\",\"string\"]},{\"default\":null,\"name\":\"cupon\",\"type\":[\"null\",\"string\"]},{\"default\":null,\"name\":\"cantidadDeEnvios\",\"type\":[\"null\",\"int\"]},{\"default\":null,\"name\":\"diasPendientes\",\"type\":[\"null\",\"int\"]},{\"default\":null,\"name\":\"tipoDeServicio\",\"type\":[\"null\",\"string\"]},{\"default\":null,\"name\":\"cuando\",\"type\":[\"null\",{\"logicalType\":\"timestamp-millis\",\"type\":\"long\"}]}],\"name\":\"Andreani.Notificaciones.Events.Records.PendienteDePago\",\"type\":\"record\"}"
}

func (r PendienteDePago) SchemaName() string {
	return "Andreani.Notificaciones.Events.Records.PendienteDePago"
}

func (_ PendienteDePago) SetBoolean(v bool)    { panic("Unsupported operation") }
func (_ PendienteDePago) SetInt(v int32)       { panic("Unsupported operation") }
func (_ PendienteDePago) SetLong(v int64)      { panic("Unsupported operation") }
func (_ PendienteDePago) SetFloat(v float32)   { panic("Unsupported operation") }
func (_ PendienteDePago) SetDouble(v float64)  { panic("Unsupported operation") }
func (_ PendienteDePago) SetBytes(v []byte)    { panic("Unsupported operation") }
func (_ PendienteDePago) SetString(v string)   { panic("Unsupported operation") }
func (_ PendienteDePago) SetUnionElem(v int64) { panic("Unsupported operation") }

func (r *PendienteDePago) Get(i int) types.Field {
	switch i {
	case 0:
		r.UsuarioId = NewUnionNullString()

		return r.UsuarioId
	case 1:
		r.Email = NewUnionNullString()

		return r.Email
	case 2:
		r.Nombre = NewUnionNullString()

		return r.Nombre
	case 3:
		r.TelefonoCodigoArea = NewUnionNullString()

		return r.TelefonoCodigoArea
	case 4:
		r.TelefonoNumero = NewUnionNullString()

		return r.TelefonoNumero
	case 5:
		r.FechaModificacion = NewUnionNullString()

		return r.FechaModificacion
	case 6:
		r.Cupon = NewUnionNullString()

		return r.Cupon
	case 7:
		r.CantidadDeEnvios = NewUnionNullInt()

		return r.CantidadDeEnvios
	case 8:
		r.DiasPendientes = NewUnionNullInt()

		return r.DiasPendientes
	case 9:
		r.TipoDeServicio = NewUnionNullString()

		return r.TipoDeServicio
	case 10:
		r.Cuando = NewUnionNullLong()

		return r.Cuando
	}
	panic("Unknown field index")
}

func (r *PendienteDePago) SetDefault(i int) {
	switch i {
	case 0:
		r.UsuarioId = nil
		return
	case 1:
		r.Email = nil
		return
	case 2:
		r.Nombre = nil
		return
	case 3:
		r.TelefonoCodigoArea = nil
		return
	case 4:
		r.TelefonoNumero = nil
		return
	case 5:
		r.FechaModificacion = nil
		return
	case 6:
		r.Cupon = nil
		return
	case 7:
		r.CantidadDeEnvios = nil
		return
	case 8:
		r.DiasPendientes = nil
		return
	case 9:
		r.TipoDeServicio = nil
		return
	case 10:
		r.Cuando = nil
		return
	}
	panic("Unknown field index")
}

func (r *PendienteDePago) NullField(i int) {
	switch i {
	case 0:
		r.UsuarioId = nil
		return
	case 1:
		r.Email = nil
		return
	case 2:
		r.Nombre = nil
		return
	case 3:
		r.TelefonoCodigoArea = nil
		return
	case 4:
		r.TelefonoNumero = nil
		return
	case 5:
		r.FechaModificacion = nil
		return
	case 6:
		r.Cupon = nil
		return
	case 7:
		r.CantidadDeEnvios = nil
		return
	case 8:
		r.DiasPendientes = nil
		return
	case 9:
		r.TipoDeServicio = nil
		return
	case 10:
		r.Cuando = nil
		return
	}
	panic("Not a nullable field index")
}

func (_ PendienteDePago) AppendMap(key string) types.Field { panic("Unsupported operation") }
func (_ PendienteDePago) AppendArray() types.Field         { panic("Unsupported operation") }
func (_ PendienteDePago) HintSize(int)                     { panic("Unsupported operation") }
func (_ PendienteDePago) Finalize()                        {}

func (_ PendienteDePago) AvroCRC64Fingerprint() []byte {
	return []byte(PendienteDePagoAvroCRC64Fingerprint)
}

func (r PendienteDePago) MarshalJSON() ([]byte, error) {
	var err error
	output := make(map[string]json.RawMessage)
	output["usuarioId"], err = json.Marshal(r.UsuarioId)
	if err != nil {
		return nil, err
	}
	output["email"], err = json.Marshal(r.Email)
	if err != nil {
		return nil, err
	}
	output["nombre"], err = json.Marshal(r.Nombre)
	if err != nil {
		return nil, err
	}
	output["telefonoCodigoArea"], err = json.Marshal(r.TelefonoCodigoArea)
	if err != nil {
		return nil, err
	}
	output["telefonoNumero"], err = json.Marshal(r.TelefonoNumero)
	if err != nil {
		return nil, err
	}
	output["fechaModificacion"], err = json.Marshal(r.FechaModificacion)
	if err != nil {
		return nil, err
	}
	output["cupon"], err = json.Marshal(r.Cupon)
	if err != nil {
		return nil, err
	}
	output["cantidadDeEnvios"], err = json.Marshal(r.CantidadDeEnvios)
	if err != nil {
		return nil, err
	}
	output["diasPendientes"], err = json.Marshal(r.DiasPendientes)
	if err != nil {
		return nil, err
	}
	output["tipoDeServicio"], err = json.Marshal(r.TipoDeServicio)
	if err != nil {
		return nil, err
	}
	output["cuando"], err = json.Marshal(r.Cuando)
	if err != nil {
		return nil, err
	}
	return json.Marshal(output)
}

func (r *PendienteDePago) UnmarshalJSON(data []byte) error {
	var fields map[string]json.RawMessage
	if err := json.Unmarshal(data, &fields); err != nil {
		return err
	}

	var val json.RawMessage
	val = func() json.RawMessage {
		if v, ok := fields["usuarioId"]; ok {
			return v
		}
		return nil
	}()

	if val != nil {
		if err := json.Unmarshal([]byte(val), &r.UsuarioId); err != nil {
			return err
		}
	} else {
		r.UsuarioId = NewUnionNullString()

		r.UsuarioId = nil
	}
	val = func() json.RawMessage {
		if v, ok := fields["email"]; ok {
			return v
		}
		return nil
	}()

	if val != nil {
		if err := json.Unmarshal([]byte(val), &r.Email); err != nil {
			return err
		}
	} else {
		r.Email = NewUnionNullString()

		r.Email = nil
	}
	val = func() json.RawMessage {
		if v, ok := fields["nombre"]; ok {
			return v
		}
		return nil
	}()

	if val != nil {
		if err := json.Unmarshal([]byte(val), &r.Nombre); err != nil {
			return err
		}
	} else {
		r.Nombre = NewUnionNullString()

		r.Nombre = nil
	}
	val = func() json.RawMessage {
		if v, ok := fields["telefonoCodigoArea"]; ok {
			return v
		}
		return nil
	}()

	if val != nil {
		if err := json.Unmarshal([]byte(val), &r.TelefonoCodigoArea); err != nil {
			return err
		}
	} else {
		r.TelefonoCodigoArea = NewUnionNullString()

		r.TelefonoCodigoArea = nil
	}
	val = func() json.RawMessage {
		if v, ok := fields["telefonoNumero"]; ok {
			return v
		}
		return nil
	}()

	if val != nil {
		if err := json.Unmarshal([]byte(val), &r.TelefonoNumero); err != nil {
			return err
		}
	} else {
		r.TelefonoNumero = NewUnionNullString()

		r.TelefonoNumero = nil
	}
	val = func() json.RawMessage {
		if v, ok := fields["fechaModificacion"]; ok {
			return v
		}
		return nil
	}()

	if val != nil {
		if err := json.Unmarshal([]byte(val), &r.FechaModificacion); err != nil {
			return err
		}
	} else {
		r.FechaModificacion = NewUnionNullString()

		r.FechaModificacion = nil
	}
	val = func() json.RawMessage {
		if v, ok := fields["cupon"]; ok {
			return v
		}
		return nil
	}()

	if val != nil {
		if err := json.Unmarshal([]byte(val), &r.Cupon); err != nil {
			return err
		}
	} else {
		r.Cupon = NewUnionNullString()

		r.Cupon = nil
	}
	val = func() json.RawMessage {
		if v, ok := fields["cantidadDeEnvios"]; ok {
			return v
		}
		return nil
	}()

	if val != nil {
		if err := json.Unmarshal([]byte(val), &r.CantidadDeEnvios); err != nil {
			return err
		}
	} else {
		r.CantidadDeEnvios = NewUnionNullInt()

		r.CantidadDeEnvios = nil
	}
	val = func() json.RawMessage {
		if v, ok := fields["diasPendientes"]; ok {
			return v
		}
		return nil
	}()

	if val != nil {
		if err := json.Unmarshal([]byte(val), &r.DiasPendientes); err != nil {
			return err
		}
	} else {
		r.DiasPendientes = NewUnionNullInt()

		r.DiasPendientes = nil
	}
	val = func() json.RawMessage {
		if v, ok := fields["tipoDeServicio"]; ok {
			return v
		}
		return nil
	}()

	if val != nil {
		if err := json.Unmarshal([]byte(val), &r.TipoDeServicio); err != nil {
			return err
		}
	} else {
		r.TipoDeServicio = NewUnionNullString()

		r.TipoDeServicio = nil
	}
	val = func() json.RawMessage {
		if v, ok := fields["cuando"]; ok {
			return v
		}
		return nil
	}()

	if val != nil {
		if err := json.Unmarshal([]byte(val), &r.Cuando); err != nil {
			return err
		}
	} else {
		r.Cuando = NewUnionNullLong()

		r.Cuando = nil
	}
	return nil
}
