// Code generated by github.com/actgardner/gogen-avro/v10. DO NOT EDIT.
/*
 * SOURCE:
 *     AvisoInactividad.avsc
 */
package NotificacionesEvents

import (
	"encoding/json"
	"fmt"
	"io"

	"github.com/actgardner/gogen-avro/v10/compiler"
	"github.com/actgardner/gogen-avro/v10/vm"
	"github.com/actgardner/gogen-avro/v10/vm/types"
)

type UnionNullRecalculoEdaTypeEnum int

const (
	UnionNullRecalculoEdaTypeEnumRecalculoEda UnionNullRecalculoEdaTypeEnum = 1
)

type UnionNullRecalculoEda struct {
	Null         *types.NullVal
	RecalculoEda RecalculoEda
	UnionType    UnionNullRecalculoEdaTypeEnum
}

func writeUnionNullRecalculoEda(r *UnionNullRecalculoEda, w io.Writer) error {

	if r == nil {
		err := vm.WriteLong(0, w)
		return err
	}

	err := vm.WriteLong(int64(r.UnionType), w)
	if err != nil {
		return err
	}
	switch r.UnionType {
	case UnionNullRecalculoEdaTypeEnumRecalculoEda:
		return writeRecalculoEda(r.RecalculoEda, w)
	}
	return fmt.Errorf("invalid value for *UnionNullRecalculoEda")
}

func NewUnionNullRecalculoEda() *UnionNullRecalculoEda {
	return &UnionNullRecalculoEda{}
}

func (r *UnionNullRecalculoEda) Serialize(w io.Writer) error {
	return writeUnionNullRecalculoEda(r, w)
}

func DeserializeUnionNullRecalculoEda(r io.Reader) (*UnionNullRecalculoEda, error) {
	t := NewUnionNullRecalculoEda()
	deser, err := compiler.CompileSchemaBytes([]byte(t.Schema()), []byte(t.Schema()))
	if err != nil {
		return t, err
	}

	err = vm.Eval(r, deser, t)

	if err != nil {
		return t, err
	}
	return t, err
}

func DeserializeUnionNullRecalculoEdaFromSchema(r io.Reader, schema string) (*UnionNullRecalculoEda, error) {
	t := NewUnionNullRecalculoEda()
	deser, err := compiler.CompileSchemaBytes([]byte(schema), []byte(t.Schema()))
	if err != nil {
		return t, err
	}

	err = vm.Eval(r, deser, t)

	if err != nil {
		return t, err
	}
	return t, err
}

func (r *UnionNullRecalculoEda) Schema() string {
	return "[\"null\",{\"fields\":[{\"default\":null,\"name\":\"tuvoRecalculo\",\"type\":[\"null\",\"boolean\"]},{\"default\":null,\"name\":\"FechaRecalculo\",\"type\":[\"null\",{\"logicalType\":\"timestamp-millis\",\"type\":\"long\"}]}],\"name\":\"RecalculoEda\",\"type\":\"record\"}]"
}

func (_ *UnionNullRecalculoEda) SetBoolean(v bool)   { panic("Unsupported operation") }
func (_ *UnionNullRecalculoEda) SetInt(v int32)      { panic("Unsupported operation") }
func (_ *UnionNullRecalculoEda) SetFloat(v float32)  { panic("Unsupported operation") }
func (_ *UnionNullRecalculoEda) SetDouble(v float64) { panic("Unsupported operation") }
func (_ *UnionNullRecalculoEda) SetBytes(v []byte)   { panic("Unsupported operation") }
func (_ *UnionNullRecalculoEda) SetString(v string)  { panic("Unsupported operation") }

func (r *UnionNullRecalculoEda) SetLong(v int64) {

	r.UnionType = (UnionNullRecalculoEdaTypeEnum)(v)
}

func (r *UnionNullRecalculoEda) Get(i int) types.Field {

	switch i {
	case 0:
		return r.Null
	case 1:
		r.RecalculoEda = NewRecalculoEda()
		return &types.Record{Target: (&r.RecalculoEda)}
	}
	panic("Unknown field index")
}
func (_ *UnionNullRecalculoEda) NullField(i int)                  { panic("Unsupported operation") }
func (_ *UnionNullRecalculoEda) HintSize(i int)                   { panic("Unsupported operation") }
func (_ *UnionNullRecalculoEda) SetDefault(i int)                 { panic("Unsupported operation") }
func (_ *UnionNullRecalculoEda) AppendMap(key string) types.Field { panic("Unsupported operation") }
func (_ *UnionNullRecalculoEda) AppendArray() types.Field         { panic("Unsupported operation") }
func (_ *UnionNullRecalculoEda) Finalize()                        {}

func (r *UnionNullRecalculoEda) MarshalJSON() ([]byte, error) {

	if r == nil {
		return []byte("null"), nil
	}

	switch r.UnionType {
	case UnionNullRecalculoEdaTypeEnumRecalculoEda:
		return json.Marshal(map[string]interface{}{"Andreani.Notificaciones.Events.Records.RecalculoEda": r.RecalculoEda})
	}
	return nil, fmt.Errorf("invalid value for *UnionNullRecalculoEda")
}

func (r *UnionNullRecalculoEda) UnmarshalJSON(data []byte) error {

	var fields map[string]json.RawMessage
	if err := json.Unmarshal(data, &fields); err != nil {
		return err
	}
	if len(fields) > 1 {
		return fmt.Errorf("more than one type supplied for union")
	}
	if value, ok := fields["Andreani.Notificaciones.Events.Records.RecalculoEda"]; ok {
		r.UnionType = 1
		return json.Unmarshal([]byte(value), &r.RecalculoEda)
	}
	return fmt.Errorf("invalid value for *UnionNullRecalculoEda")
}
