// Code generated by github.com/actgardner/gogen-avro/v10. DO NOT EDIT.
/*
 * SOURCE:
 *     EventoWhArticuloActualizacion.avsc
 */
package EventoWhSceEventUpdateEvents

import (
	"io"

	"github.com/actgardner/gogen-avro/v10/vm"
	"github.com/actgardner/gogen-avro/v10/vm/types"
)

func writeArrayArticuloAltSku(r []ArticuloAltSku, w io.Writer) error {
	err := vm.WriteLong(int64(len(r)), w)
	if err != nil || len(r) == 0 {
		return err
	}
	for _, e := range r {
		err = writeArticuloAltSku(e, w)
		if err != nil {
			return err
		}
	}
	return vm.WriteLong(0, w)
}

type ArrayArticuloAltSkuWrapper struct {
	Target *[]ArticuloAltSku
}

func (_ ArrayArticuloAltSkuWrapper) SetBoolean(v bool)                { panic("Unsupported operation") }
func (_ ArrayArticuloAltSkuWrapper) SetInt(v int32)                   { panic("Unsupported operation") }
func (_ ArrayArticuloAltSkuWrapper) SetLong(v int64)                  { panic("Unsupported operation") }
func (_ ArrayArticuloAltSkuWrapper) SetFloat(v float32)               { panic("Unsupported operation") }
func (_ ArrayArticuloAltSkuWrapper) SetDouble(v float64)              { panic("Unsupported operation") }
func (_ ArrayArticuloAltSkuWrapper) SetBytes(v []byte)                { panic("Unsupported operation") }
func (_ ArrayArticuloAltSkuWrapper) SetString(v string)               { panic("Unsupported operation") }
func (_ ArrayArticuloAltSkuWrapper) SetUnionElem(v int64)             { panic("Unsupported operation") }
func (_ ArrayArticuloAltSkuWrapper) Get(i int) types.Field            { panic("Unsupported operation") }
func (_ ArrayArticuloAltSkuWrapper) AppendMap(key string) types.Field { panic("Unsupported operation") }
func (_ ArrayArticuloAltSkuWrapper) Finalize()                        {}
func (_ ArrayArticuloAltSkuWrapper) SetDefault(i int)                 { panic("Unsupported operation") }
func (r ArrayArticuloAltSkuWrapper) HintSize(s int) {
	if len(*r.Target) == 0 {
		*r.Target = make([]ArticuloAltSku, 0, s)
	}
}
func (r ArrayArticuloAltSkuWrapper) NullField(i int) {
	panic("Unsupported operation")
}

func (r ArrayArticuloAltSkuWrapper) AppendArray() types.Field {
	var v ArticuloAltSku
	v = NewArticuloAltSku()

	*r.Target = append(*r.Target, v)
	return &types.Record{Target: &(*r.Target)[len(*r.Target)-1]}
}
