// Code generated by github.com/actgardner/gogen-avro/v10. DO NOT EDIT.
/*
 * SOURCE:
 *     trigger.avsc
 */
package EmpaquetadoEvents

import (
	"encoding/json"
	"fmt"
	"io"

	"github.com/actgardner/gogen-avro/v10/compiler"
	"github.com/actgardner/gogen-avro/v10/vm"
	"github.com/actgardner/gogen-avro/v10/vm/types"
)

var _ = fmt.Printf

type Trigger struct {
	Trigger *UnionNullString `json:"Trigger"`
}

const TriggerAvroCRC64Fingerprint = "9\x92\xf7\xe6\xda\x14{6"

func NewTrigger() Trigger {
	r := Trigger{}
	r.Trigger = nil
	return r
}

func DeserializeTrigger(r io.Reader) (Trigger, error) {
	t := NewTrigger()
	deser, err := compiler.CompileSchemaBytes([]byte(t.Schema()), []byte(t.Schema()))
	if err != nil {
		return t, err
	}

	err = vm.Eval(r, deser, &t)
	return t, err
}

func DeserializeTriggerFromSchema(r io.Reader, schema string) (Trigger, error) {
	t := NewTrigger()

	deser, err := compiler.CompileSchemaBytes([]byte(schema), []byte(t.Schema()))
	if err != nil {
		return t, err
	}

	err = vm.Eval(r, deser, &t)
	return t, err
}

func writeTrigger(r Trigger, w io.Writer) error {
	var err error
	err = writeUnionNullString(r.Trigger, w)
	if err != nil {
		return err
	}
	return err
}

func (r Trigger) Serialize(w io.Writer) error {
	return writeTrigger(r, w)
}

func (r Trigger) Schema() string {
	return "{\"fields\":[{\"default\":null,\"name\":\"Trigger\",\"type\":[\"null\",\"string\"]}],\"name\":\"Andreani.Empaquetado.Events.Record.trigger\",\"type\":\"record\"}"
}

func (r Trigger) SchemaName() string {
	return "Andreani.Empaquetado.Events.Record.trigger"
}

func (_ Trigger) SetBoolean(v bool)    { panic("Unsupported operation") }
func (_ Trigger) SetInt(v int32)       { panic("Unsupported operation") }
func (_ Trigger) SetLong(v int64)      { panic("Unsupported operation") }
func (_ Trigger) SetFloat(v float32)   { panic("Unsupported operation") }
func (_ Trigger) SetDouble(v float64)  { panic("Unsupported operation") }
func (_ Trigger) SetBytes(v []byte)    { panic("Unsupported operation") }
func (_ Trigger) SetString(v string)   { panic("Unsupported operation") }
func (_ Trigger) SetUnionElem(v int64) { panic("Unsupported operation") }

func (r *Trigger) Get(i int) types.Field {
	switch i {
	case 0:
		r.Trigger = NewUnionNullString()

		return r.Trigger
	}
	panic("Unknown field index")
}

func (r *Trigger) SetDefault(i int) {
	switch i {
	case 0:
		r.Trigger = nil
		return
	}
	panic("Unknown field index")
}

func (r *Trigger) NullField(i int) {
	switch i {
	case 0:
		r.Trigger = nil
		return
	}
	panic("Not a nullable field index")
}

func (_ Trigger) AppendMap(key string) types.Field { panic("Unsupported operation") }
func (_ Trigger) AppendArray() types.Field         { panic("Unsupported operation") }
func (_ Trigger) HintSize(int)                     { panic("Unsupported operation") }
func (_ Trigger) Finalize()                        {}

func (_ Trigger) AvroCRC64Fingerprint() []byte {
	return []byte(TriggerAvroCRC64Fingerprint)
}

func (r Trigger) MarshalJSON() ([]byte, error) {
	var err error
	output := make(map[string]json.RawMessage)
	output["Trigger"], err = json.Marshal(r.Trigger)
	if err != nil {
		return nil, err
	}
	return json.Marshal(output)
}

func (r *Trigger) UnmarshalJSON(data []byte) error {
	var fields map[string]json.RawMessage
	if err := json.Unmarshal(data, &fields); err != nil {
		return err
	}

	var val json.RawMessage
	val = func() json.RawMessage {
		if v, ok := fields["Trigger"]; ok {
			return v
		}
		return nil
	}()

	if val != nil {
		if err := json.Unmarshal([]byte(val), &r.Trigger); err != nil {
			return err
		}
	} else {
		r.Trigger = NewUnionNullString()

		r.Trigger = nil
	}
	return nil
}
