// Code generated by github.com/actgardner/gogen-avro/v10. DO NOT EDIT.
/*
 * SOURCE:
 *     ItemsMeliNotificationEvent.avsc
 */
package MEunoApiEvents

import (
	"encoding/json"
	"fmt"
	"io"

	"github.com/actgardner/gogen-avro/v10/compiler"
	"github.com/actgardner/gogen-avro/v10/vm"
	"github.com/actgardner/gogen-avro/v10/vm/types"
)

var _ = fmt.Printf

type ItemsMeliNotificationEvent struct {
	SellerId int64 `json:"SellerId"`

	ItemId string `json:"ItemId"`
}

const ItemsMeliNotificationEventAvroCRC64Fingerprint = "\xfaŠ\x01\t\xbeh\x95"

func NewItemsMeliNotificationEvent() ItemsMeliNotificationEvent {
	r := ItemsMeliNotificationEvent{}
	return r
}

func DeserializeItemsMeliNotificationEvent(r io.Reader) (ItemsMeliNotificationEvent, error) {
	t := NewItemsMeliNotificationEvent()
	deser, err := compiler.CompileSchemaBytes([]byte(t.Schema()), []byte(t.Schema()))
	if err != nil {
		return t, err
	}

	err = vm.Eval(r, deser, &t)
	return t, err
}

func DeserializeItemsMeliNotificationEventFromSchema(r io.Reader, schema string) (ItemsMeliNotificationEvent, error) {
	t := NewItemsMeliNotificationEvent()

	deser, err := compiler.CompileSchemaBytes([]byte(schema), []byte(t.Schema()))
	if err != nil {
		return t, err
	}

	err = vm.Eval(r, deser, &t)
	return t, err
}

func writeItemsMeliNotificationEvent(r ItemsMeliNotificationEvent, w io.Writer) error {
	var err error
	err = vm.WriteLong(r.SellerId, w)
	if err != nil {
		return err
	}
	err = vm.WriteString(r.ItemId, w)
	if err != nil {
		return err
	}
	return err
}

func (r ItemsMeliNotificationEvent) Serialize(w io.Writer) error {
	return writeItemsMeliNotificationEvent(r, w)
}

func (r ItemsMeliNotificationEvent) Schema() string {
	return "{\"fields\":[{\"name\":\"SellerId\",\"type\":\"long\"},{\"name\":\"ItemId\",\"type\":\"string\"}],\"name\":\"Andreani.MEunoApi.Events.Record.ItemsMeliNotificationEvent\",\"type\":\"record\"}"
}

func (r ItemsMeliNotificationEvent) SchemaName() string {
	return "Andreani.MEunoApi.Events.Record.ItemsMeliNotificationEvent"
}

func (_ ItemsMeliNotificationEvent) SetBoolean(v bool)    { panic("Unsupported operation") }
func (_ ItemsMeliNotificationEvent) SetInt(v int32)       { panic("Unsupported operation") }
func (_ ItemsMeliNotificationEvent) SetLong(v int64)      { panic("Unsupported operation") }
func (_ ItemsMeliNotificationEvent) SetFloat(v float32)   { panic("Unsupported operation") }
func (_ ItemsMeliNotificationEvent) SetDouble(v float64)  { panic("Unsupported operation") }
func (_ ItemsMeliNotificationEvent) SetBytes(v []byte)    { panic("Unsupported operation") }
func (_ ItemsMeliNotificationEvent) SetString(v string)   { panic("Unsupported operation") }
func (_ ItemsMeliNotificationEvent) SetUnionElem(v int64) { panic("Unsupported operation") }

func (r *ItemsMeliNotificationEvent) Get(i int) types.Field {
	switch i {
	case 0:
		w := types.Long{Target: &r.SellerId}

		return w

	case 1:
		w := types.String{Target: &r.ItemId}

		return w

	}
	panic("Unknown field index")
}

func (r *ItemsMeliNotificationEvent) SetDefault(i int) {
	switch i {
	}
	panic("Unknown field index")
}

func (r *ItemsMeliNotificationEvent) NullField(i int) {
	switch i {
	}
	panic("Not a nullable field index")
}

func (_ ItemsMeliNotificationEvent) AppendMap(key string) types.Field { panic("Unsupported operation") }
func (_ ItemsMeliNotificationEvent) AppendArray() types.Field         { panic("Unsupported operation") }
func (_ ItemsMeliNotificationEvent) HintSize(int)                     { panic("Unsupported operation") }
func (_ ItemsMeliNotificationEvent) Finalize()                        {}

func (_ ItemsMeliNotificationEvent) AvroCRC64Fingerprint() []byte {
	return []byte(ItemsMeliNotificationEventAvroCRC64Fingerprint)
}

func (r ItemsMeliNotificationEvent) MarshalJSON() ([]byte, error) {
	var err error
	output := make(map[string]json.RawMessage)
	output["SellerId"], err = json.Marshal(r.SellerId)
	if err != nil {
		return nil, err
	}
	output["ItemId"], err = json.Marshal(r.ItemId)
	if err != nil {
		return nil, err
	}
	return json.Marshal(output)
}

func (r *ItemsMeliNotificationEvent) UnmarshalJSON(data []byte) error {
	var fields map[string]json.RawMessage
	if err := json.Unmarshal(data, &fields); err != nil {
		return err
	}

	var val json.RawMessage
	val = func() json.RawMessage {
		if v, ok := fields["SellerId"]; ok {
			return v
		}
		return nil
	}()

	if val != nil {
		if err := json.Unmarshal([]byte(val), &r.SellerId); err != nil {
			return err
		}
	} else {
		return fmt.Errorf("no value specified for SellerId")
	}
	val = func() json.RawMessage {
		if v, ok := fields["ItemId"]; ok {
			return v
		}
		return nil
	}()

	if val != nil {
		if err := json.Unmarshal([]byte(val), &r.ItemId); err != nil {
			return err
		}
	} else {
		return fmt.Errorf("no value specified for ItemId")
	}
	return nil
}
