// Code generated by github.com/actgardner/gogen-avro/v10. DO NOT EDIT.
/*
 * SOURCE:
 *     ClienteInformaNoEsProductoSolicitado.avsc
 */
package TrazasEvents

import (
	"encoding/json"
	"fmt"
	"io"

	"github.com/actgardner/gogen-avro/v10/compiler"
	"github.com/actgardner/gogen-avro/v10/vm"
	"github.com/actgardner/gogen-avro/v10/vm/types"
)

var _ = fmt.Printf

type ClienteInformaNoEsProductoSolicitado struct {
	Traza Traza `json:"traza"`
}

const ClienteInformaNoEsProductoSolicitadoAvroCRC64Fingerprint = "\xa9\xf6\x9a\ny\x9e\x86\x87"

func NewClienteInformaNoEsProductoSolicitado() ClienteInformaNoEsProductoSolicitado {
	r := ClienteInformaNoEsProductoSolicitado{}
	r.Traza = NewTraza()

	return r
}

func DeserializeClienteInformaNoEsProductoSolicitado(r io.Reader) (ClienteInformaNoEsProductoSolicitado, error) {
	t := NewClienteInformaNoEsProductoSolicitado()
	deser, err := compiler.CompileSchemaBytes([]byte(t.Schema()), []byte(t.Schema()))
	if err != nil {
		return t, err
	}

	err = vm.Eval(r, deser, &t)
	return t, err
}

func DeserializeClienteInformaNoEsProductoSolicitadoFromSchema(r io.Reader, schema string) (ClienteInformaNoEsProductoSolicitado, error) {
	t := NewClienteInformaNoEsProductoSolicitado()

	deser, err := compiler.CompileSchemaBytes([]byte(schema), []byte(t.Schema()))
	if err != nil {
		return t, err
	}

	err = vm.Eval(r, deser, &t)
	return t, err
}

func writeClienteInformaNoEsProductoSolicitado(r ClienteInformaNoEsProductoSolicitado, w io.Writer) error {
	var err error
	err = writeTraza(r.Traza, w)
	if err != nil {
		return err
	}
	return err
}

func (r ClienteInformaNoEsProductoSolicitado) Serialize(w io.Writer) error {
	return writeClienteInformaNoEsProductoSolicitado(r, w)
}

func (r ClienteInformaNoEsProductoSolicitado) Schema() string {
	return "{\"fields\":[{\"name\":\"traza\",\"type\":{\"fields\":[{\"name\":\"codigoDeEnvio\",\"type\":\"string\"},{\"default\":null,\"name\":\"nombre\",\"type\":[\"null\",\"string\"]},{\"name\":\"cuando\",\"type\":{\"logicalType\":\"timestamp-millis\",\"type\":\"long\"}},{\"name\":\"codigoDeContratoInterno\",\"type\":\"string\"},{\"default\":null,\"name\":\"codigoDeContrato\",\"type\":[\"null\",\"string\"]},{\"default\":null,\"name\":\"estadoDelEnvio\",\"type\":[\"null\",\"string\"]},{\"default\":null,\"name\":\"cicloDelEnvio\",\"type\":[\"null\",\"string\"]},{\"default\":null,\"name\":\"operador\",\"type\":[\"null\",\"string\"]},{\"default\":null,\"name\":\"estadoDeLaRendicion\",\"type\":[\"null\",\"string\"]},{\"default\":null,\"name\":\"comentario\",\"type\":[\"null\",\"string\"]},{\"default\":null,\"name\":\"sucursalAsociadaAlEvento\",\"type\":[\"null\",{\"fields\":[{\"name\":\"codigo\",\"type\":\"string\"},{\"default\":null,\"name\":\"nombre\",\"type\":[\"null\",\"string\"]},{\"name\":\"id\",\"type\":\"string\"}],\"name\":\"DatosSucursal\",\"namespace\":\"Integracion.Esquemas.Referencias\",\"type\":\"record\"}]}],\"name\":\"Traza\",\"namespace\":\"Integracion.Esquemas\",\"type\":\"record\"}}],\"name\":\"Integracion.Esquemas.Trazas.ClienteInformaNoEsProductoSolicitado\",\"type\":\"record\"}"
}

func (r ClienteInformaNoEsProductoSolicitado) SchemaName() string {
	return "Integracion.Esquemas.Trazas.ClienteInformaNoEsProductoSolicitado"
}

func (_ ClienteInformaNoEsProductoSolicitado) SetBoolean(v bool)    { panic("Unsupported operation") }
func (_ ClienteInformaNoEsProductoSolicitado) SetInt(v int32)       { panic("Unsupported operation") }
func (_ ClienteInformaNoEsProductoSolicitado) SetLong(v int64)      { panic("Unsupported operation") }
func (_ ClienteInformaNoEsProductoSolicitado) SetFloat(v float32)   { panic("Unsupported operation") }
func (_ ClienteInformaNoEsProductoSolicitado) SetDouble(v float64)  { panic("Unsupported operation") }
func (_ ClienteInformaNoEsProductoSolicitado) SetBytes(v []byte)    { panic("Unsupported operation") }
func (_ ClienteInformaNoEsProductoSolicitado) SetString(v string)   { panic("Unsupported operation") }
func (_ ClienteInformaNoEsProductoSolicitado) SetUnionElem(v int64) { panic("Unsupported operation") }

func (r *ClienteInformaNoEsProductoSolicitado) Get(i int) types.Field {
	switch i {
	case 0:
		r.Traza = NewTraza()

		w := types.Record{Target: &r.Traza}

		return w

	}
	panic("Unknown field index")
}

func (r *ClienteInformaNoEsProductoSolicitado) SetDefault(i int) {
	switch i {
	}
	panic("Unknown field index")
}

func (r *ClienteInformaNoEsProductoSolicitado) NullField(i int) {
	switch i {
	}
	panic("Not a nullable field index")
}

func (_ ClienteInformaNoEsProductoSolicitado) AppendMap(key string) types.Field {
	panic("Unsupported operation")
}
func (_ ClienteInformaNoEsProductoSolicitado) AppendArray() types.Field {
	panic("Unsupported operation")
}
func (_ ClienteInformaNoEsProductoSolicitado) HintSize(int) { panic("Unsupported operation") }
func (_ ClienteInformaNoEsProductoSolicitado) Finalize()    {}

func (_ ClienteInformaNoEsProductoSolicitado) AvroCRC64Fingerprint() []byte {
	return []byte(ClienteInformaNoEsProductoSolicitadoAvroCRC64Fingerprint)
}

func (r ClienteInformaNoEsProductoSolicitado) MarshalJSON() ([]byte, error) {
	var err error
	output := make(map[string]json.RawMessage)
	output["traza"], err = json.Marshal(r.Traza)
	if err != nil {
		return nil, err
	}
	return json.Marshal(output)
}

func (r *ClienteInformaNoEsProductoSolicitado) UnmarshalJSON(data []byte) error {
	var fields map[string]json.RawMessage
	if err := json.Unmarshal(data, &fields); err != nil {
		return err
	}

	var val json.RawMessage
	val = func() json.RawMessage {
		if v, ok := fields["traza"]; ok {
			return v
		}
		return nil
	}()

	if val != nil {
		if err := json.Unmarshal([]byte(val), &r.Traza); err != nil {
			return err
		}
	} else {
		return fmt.Errorf("no value specified for traza")
	}
	return nil
}
