// Code generated by github.com/actgardner/gogen-avro/v10. DO NOT EDIT.
/*
 * SOURCE:
 *     ContenedorConReferenciaExterna.avsc
 */
package TrazasEvents

import (
	"encoding/json"
	"fmt"
	"io"

	"github.com/actgardner/gogen-avro/v10/compiler"
	"github.com/actgardner/gogen-avro/v10/vm"
	"github.com/actgardner/gogen-avro/v10/vm/types"
)

var _ = fmt.Printf

type ContenedorConReferenciaExterna struct {
	Traza TrazaContendor `json:"traza"`

	NumeroReferencia *UnionNullString `json:"numeroReferencia"`
}

const ContenedorConReferenciaExternaAvroCRC64Fingerprint = "\xb5\xc6TAD\xe4\xb5\xcd"

func NewContenedorConReferenciaExterna() ContenedorConReferenciaExterna {
	r := ContenedorConReferenciaExterna{}
	r.Traza = NewTrazaContendor()

	r.NumeroReferencia = nil
	return r
}

func DeserializeContenedorConReferenciaExterna(r io.Reader) (ContenedorConReferenciaExterna, error) {
	t := NewContenedorConReferenciaExterna()
	deser, err := compiler.CompileSchemaBytes([]byte(t.Schema()), []byte(t.Schema()))
	if err != nil {
		return t, err
	}

	err = vm.Eval(r, deser, &t)
	return t, err
}

func DeserializeContenedorConReferenciaExternaFromSchema(r io.Reader, schema string) (ContenedorConReferenciaExterna, error) {
	t := NewContenedorConReferenciaExterna()

	deser, err := compiler.CompileSchemaBytes([]byte(schema), []byte(t.Schema()))
	if err != nil {
		return t, err
	}

	err = vm.Eval(r, deser, &t)
	return t, err
}

func writeContenedorConReferenciaExterna(r ContenedorConReferenciaExterna, w io.Writer) error {
	var err error
	err = writeTrazaContendor(r.Traza, w)
	if err != nil {
		return err
	}
	err = writeUnionNullString(r.NumeroReferencia, w)
	if err != nil {
		return err
	}
	return err
}

func (r ContenedorConReferenciaExterna) Serialize(w io.Writer) error {
	return writeContenedorConReferenciaExterna(r, w)
}

func (r ContenedorConReferenciaExterna) Schema() string {
	return "{\"fields\":[{\"name\":\"traza\",\"type\":{\"fields\":[{\"name\":\"numero\",\"type\":\"string\"},{\"name\":\"tipo\",\"type\":\"string\"},{\"name\":\"ciclo\",\"type\":\"string\"},{\"name\":\"estado\",\"type\":\"string\"},{\"name\":\"cuando\",\"type\":{\"logicalType\":\"timestamp-millis\",\"type\":\"long\"}},{\"default\":null,\"name\":\"operador\",\"type\":[\"null\",\"string\"]},{\"default\":null,\"name\":\"comentario\",\"type\":[\"null\",\"string\"]},{\"default\":null,\"name\":\"prefijo\",\"type\":[\"null\",\"string\"]},{\"default\":null,\"name\":\"sucursalAsociadaAlEvento\",\"type\":[\"null\",{\"fields\":[{\"name\":\"codigo\",\"type\":\"string\"},{\"default\":null,\"name\":\"nombre\",\"type\":[\"null\",\"string\"]},{\"name\":\"id\",\"type\":\"string\"}],\"name\":\"DatosSucursal\",\"namespace\":\"Integracion.Esquemas.Referencias\",\"type\":\"record\"}]}],\"name\":\"TrazaContendor\",\"namespace\":\"Integracion.Esquemas.Contenedor.Referencias\",\"type\":\"record\"}},{\"default\":null,\"name\":\"numeroReferencia\",\"type\":[\"null\",\"string\"]}],\"name\":\"Integracion.Esquemas.Contenedor.Trazas.ContenedorConReferenciaExterna\",\"type\":\"record\"}"
}

func (r ContenedorConReferenciaExterna) SchemaName() string {
	return "Integracion.Esquemas.Contenedor.Trazas.ContenedorConReferenciaExterna"
}

func (_ ContenedorConReferenciaExterna) SetBoolean(v bool)    { panic("Unsupported operation") }
func (_ ContenedorConReferenciaExterna) SetInt(v int32)       { panic("Unsupported operation") }
func (_ ContenedorConReferenciaExterna) SetLong(v int64)      { panic("Unsupported operation") }
func (_ ContenedorConReferenciaExterna) SetFloat(v float32)   { panic("Unsupported operation") }
func (_ ContenedorConReferenciaExterna) SetDouble(v float64)  { panic("Unsupported operation") }
func (_ ContenedorConReferenciaExterna) SetBytes(v []byte)    { panic("Unsupported operation") }
func (_ ContenedorConReferenciaExterna) SetString(v string)   { panic("Unsupported operation") }
func (_ ContenedorConReferenciaExterna) SetUnionElem(v int64) { panic("Unsupported operation") }

func (r *ContenedorConReferenciaExterna) Get(i int) types.Field {
	switch i {
	case 0:
		r.Traza = NewTrazaContendor()

		w := types.Record{Target: &r.Traza}

		return w

	case 1:
		r.NumeroReferencia = NewUnionNullString()

		return r.NumeroReferencia
	}
	panic("Unknown field index")
}

func (r *ContenedorConReferenciaExterna) SetDefault(i int) {
	switch i {
	case 1:
		r.NumeroReferencia = nil
		return
	}
	panic("Unknown field index")
}

func (r *ContenedorConReferenciaExterna) NullField(i int) {
	switch i {
	case 1:
		r.NumeroReferencia = nil
		return
	}
	panic("Not a nullable field index")
}

func (_ ContenedorConReferenciaExterna) AppendMap(key string) types.Field {
	panic("Unsupported operation")
}
func (_ ContenedorConReferenciaExterna) AppendArray() types.Field { panic("Unsupported operation") }
func (_ ContenedorConReferenciaExterna) HintSize(int)             { panic("Unsupported operation") }
func (_ ContenedorConReferenciaExterna) Finalize()                {}

func (_ ContenedorConReferenciaExterna) AvroCRC64Fingerprint() []byte {
	return []byte(ContenedorConReferenciaExternaAvroCRC64Fingerprint)
}

func (r ContenedorConReferenciaExterna) MarshalJSON() ([]byte, error) {
	var err error
	output := make(map[string]json.RawMessage)
	output["traza"], err = json.Marshal(r.Traza)
	if err != nil {
		return nil, err
	}
	output["numeroReferencia"], err = json.Marshal(r.NumeroReferencia)
	if err != nil {
		return nil, err
	}
	return json.Marshal(output)
}

func (r *ContenedorConReferenciaExterna) UnmarshalJSON(data []byte) error {
	var fields map[string]json.RawMessage
	if err := json.Unmarshal(data, &fields); err != nil {
		return err
	}

	var val json.RawMessage
	val = func() json.RawMessage {
		if v, ok := fields["traza"]; ok {
			return v
		}
		return nil
	}()

	if val != nil {
		if err := json.Unmarshal([]byte(val), &r.Traza); err != nil {
			return err
		}
	} else {
		return fmt.Errorf("no value specified for traza")
	}
	val = func() json.RawMessage {
		if v, ok := fields["numeroReferencia"]; ok {
			return v
		}
		return nil
	}()

	if val != nil {
		if err := json.Unmarshal([]byte(val), &r.NumeroReferencia); err != nil {
			return err
		}
	} else {
		r.NumeroReferencia = NewUnionNullString()

		r.NumeroReferencia = nil
	}
	return nil
}
