// Code generated by github.com/actgardner/gogen-avro/v10. DO NOT EDIT.
/*
 * SOURCE:
 *     EliminarMarcaDeRescate.avsc
 */
package TrazasEvents

import (
	"encoding/json"
	"fmt"
	"io"

	"github.com/actgardner/gogen-avro/v10/compiler"
	"github.com/actgardner/gogen-avro/v10/vm"
	"github.com/actgardner/gogen-avro/v10/vm/types"
)

var _ = fmt.Printf

type EliminarMarcaDeRescate struct {
	Traza Traza `json:"traza"`
}

const EliminarMarcaDeRescateAvroCRC64Fingerprint = "\xaf+\xb5I\xed_\xa2\x14"

func NewEliminarMarcaDeRescate() EliminarMarcaDeRescate {
	r := EliminarMarcaDeRescate{}
	r.Traza = NewTraza()

	return r
}

func DeserializeEliminarMarcaDeRescate(r io.Reader) (EliminarMarcaDeRescate, error) {
	t := NewEliminarMarcaDeRescate()
	deser, err := compiler.CompileSchemaBytes([]byte(t.Schema()), []byte(t.Schema()))
	if err != nil {
		return t, err
	}

	err = vm.Eval(r, deser, &t)
	return t, err
}

func DeserializeEliminarMarcaDeRescateFromSchema(r io.Reader, schema string) (EliminarMarcaDeRescate, error) {
	t := NewEliminarMarcaDeRescate()

	deser, err := compiler.CompileSchemaBytes([]byte(schema), []byte(t.Schema()))
	if err != nil {
		return t, err
	}

	err = vm.Eval(r, deser, &t)
	return t, err
}

func writeEliminarMarcaDeRescate(r EliminarMarcaDeRescate, w io.Writer) error {
	var err error
	err = writeTraza(r.Traza, w)
	if err != nil {
		return err
	}
	return err
}

func (r EliminarMarcaDeRescate) Serialize(w io.Writer) error {
	return writeEliminarMarcaDeRescate(r, w)
}

func (r EliminarMarcaDeRescate) Schema() string {
	return "{\"fields\":[{\"name\":\"traza\",\"type\":{\"fields\":[{\"name\":\"codigoDeEnvio\",\"type\":\"string\"},{\"default\":null,\"name\":\"nombre\",\"type\":[\"null\",\"string\"]},{\"name\":\"cuando\",\"type\":{\"logicalType\":\"timestamp-millis\",\"type\":\"long\"}},{\"name\":\"codigoDeContratoInterno\",\"type\":\"string\"},{\"default\":null,\"name\":\"codigoDeContrato\",\"type\":[\"null\",\"string\"]},{\"default\":null,\"name\":\"estadoDelEnvio\",\"type\":[\"null\",\"string\"]},{\"default\":null,\"name\":\"cicloDelEnvio\",\"type\":[\"null\",\"string\"]},{\"default\":null,\"name\":\"operador\",\"type\":[\"null\",\"string\"]},{\"default\":null,\"name\":\"estadoDeLaRendicion\",\"type\":[\"null\",\"string\"]},{\"default\":null,\"name\":\"comentario\",\"type\":[\"null\",\"string\"]},{\"default\":null,\"name\":\"sucursalAsociadaAlEvento\",\"type\":[\"null\",{\"fields\":[{\"name\":\"codigo\",\"type\":\"string\"},{\"default\":null,\"name\":\"nombre\",\"type\":[\"null\",\"string\"]},{\"name\":\"id\",\"type\":\"string\"}],\"name\":\"DatosSucursal\",\"namespace\":\"Integracion.Esquemas.Referencias\",\"type\":\"record\"}]}],\"name\":\"Traza\",\"namespace\":\"Integracion.Esquemas\",\"type\":\"record\"}}],\"name\":\"Integracion.Esquemas.Trazas.EliminarMarcaDeRescate\",\"type\":\"record\"}"
}

func (r EliminarMarcaDeRescate) SchemaName() string {
	return "Integracion.Esquemas.Trazas.EliminarMarcaDeRescate"
}

func (_ EliminarMarcaDeRescate) SetBoolean(v bool)    { panic("Unsupported operation") }
func (_ EliminarMarcaDeRescate) SetInt(v int32)       { panic("Unsupported operation") }
func (_ EliminarMarcaDeRescate) SetLong(v int64)      { panic("Unsupported operation") }
func (_ EliminarMarcaDeRescate) SetFloat(v float32)   { panic("Unsupported operation") }
func (_ EliminarMarcaDeRescate) SetDouble(v float64)  { panic("Unsupported operation") }
func (_ EliminarMarcaDeRescate) SetBytes(v []byte)    { panic("Unsupported operation") }
func (_ EliminarMarcaDeRescate) SetString(v string)   { panic("Unsupported operation") }
func (_ EliminarMarcaDeRescate) SetUnionElem(v int64) { panic("Unsupported operation") }

func (r *EliminarMarcaDeRescate) Get(i int) types.Field {
	switch i {
	case 0:
		r.Traza = NewTraza()

		w := types.Record{Target: &r.Traza}

		return w

	}
	panic("Unknown field index")
}

func (r *EliminarMarcaDeRescate) SetDefault(i int) {
	switch i {
	}
	panic("Unknown field index")
}

func (r *EliminarMarcaDeRescate) NullField(i int) {
	switch i {
	}
	panic("Not a nullable field index")
}

func (_ EliminarMarcaDeRescate) AppendMap(key string) types.Field { panic("Unsupported operation") }
func (_ EliminarMarcaDeRescate) AppendArray() types.Field         { panic("Unsupported operation") }
func (_ EliminarMarcaDeRescate) HintSize(int)                     { panic("Unsupported operation") }
func (_ EliminarMarcaDeRescate) Finalize()                        {}

func (_ EliminarMarcaDeRescate) AvroCRC64Fingerprint() []byte {
	return []byte(EliminarMarcaDeRescateAvroCRC64Fingerprint)
}

func (r EliminarMarcaDeRescate) MarshalJSON() ([]byte, error) {
	var err error
	output := make(map[string]json.RawMessage)
	output["traza"], err = json.Marshal(r.Traza)
	if err != nil {
		return nil, err
	}
	return json.Marshal(output)
}

func (r *EliminarMarcaDeRescate) UnmarshalJSON(data []byte) error {
	var fields map[string]json.RawMessage
	if err := json.Unmarshal(data, &fields); err != nil {
		return err
	}

	var val json.RawMessage
	val = func() json.RawMessage {
		if v, ok := fields["traza"]; ok {
			return v
		}
		return nil
	}()

	if val != nil {
		if err := json.Unmarshal([]byte(val), &r.Traza); err != nil {
			return err
		}
	} else {
		return fmt.Errorf("no value specified for traza")
	}
	return nil
}
