// Code generated by github.com/actgardner/gogen-avro/v10. DO NOT EDIT.
/*
 * SOURCE:
 *     EnvioSaleReacondicionamiento.avsc
 */
package TrazasEvents

import (
	"encoding/json"
	"fmt"
	"io"

	"github.com/actgardner/gogen-avro/v10/compiler"
	"github.com/actgardner/gogen-avro/v10/vm"
	"github.com/actgardner/gogen-avro/v10/vm/types"
)

var _ = fmt.Printf

type EnvioSaleReacondicionamiento struct {
	Traza Traza `json:"traza"`
}

const EnvioSaleReacondicionamientoAvroCRC64Fingerprint = "\xcf%\x8d%\xfbwS\xfb"

func NewEnvioSaleReacondicionamiento() EnvioSaleReacondicionamiento {
	r := EnvioSaleReacondicionamiento{}
	r.Traza = NewTraza()

	return r
}

func DeserializeEnvioSaleReacondicionamiento(r io.Reader) (EnvioSaleReacondicionamiento, error) {
	t := NewEnvioSaleReacondicionamiento()
	deser, err := compiler.CompileSchemaBytes([]byte(t.Schema()), []byte(t.Schema()))
	if err != nil {
		return t, err
	}

	err = vm.Eval(r, deser, &t)
	return t, err
}

func DeserializeEnvioSaleReacondicionamientoFromSchema(r io.Reader, schema string) (EnvioSaleReacondicionamiento, error) {
	t := NewEnvioSaleReacondicionamiento()

	deser, err := compiler.CompileSchemaBytes([]byte(schema), []byte(t.Schema()))
	if err != nil {
		return t, err
	}

	err = vm.Eval(r, deser, &t)
	return t, err
}

func writeEnvioSaleReacondicionamiento(r EnvioSaleReacondicionamiento, w io.Writer) error {
	var err error
	err = writeTraza(r.Traza, w)
	if err != nil {
		return err
	}
	return err
}

func (r EnvioSaleReacondicionamiento) Serialize(w io.Writer) error {
	return writeEnvioSaleReacondicionamiento(r, w)
}

func (r EnvioSaleReacondicionamiento) Schema() string {
	return "{\"fields\":[{\"name\":\"traza\",\"type\":{\"fields\":[{\"name\":\"codigoDeEnvio\",\"type\":\"string\"},{\"default\":null,\"name\":\"nombre\",\"type\":[\"null\",\"string\"]},{\"name\":\"cuando\",\"type\":{\"logicalType\":\"timestamp-millis\",\"type\":\"long\"}},{\"name\":\"codigoDeContratoInterno\",\"type\":\"string\"},{\"default\":null,\"name\":\"codigoDeContrato\",\"type\":[\"null\",\"string\"]},{\"default\":null,\"name\":\"estadoDelEnvio\",\"type\":[\"null\",\"string\"]},{\"default\":null,\"name\":\"cicloDelEnvio\",\"type\":[\"null\",\"string\"]},{\"default\":null,\"name\":\"operador\",\"type\":[\"null\",\"string\"]},{\"default\":null,\"name\":\"estadoDeLaRendicion\",\"type\":[\"null\",\"string\"]},{\"default\":null,\"name\":\"comentario\",\"type\":[\"null\",\"string\"]},{\"default\":null,\"name\":\"sucursalAsociadaAlEvento\",\"type\":[\"null\",{\"fields\":[{\"name\":\"codigo\",\"type\":\"string\"},{\"default\":null,\"name\":\"nombre\",\"type\":[\"null\",\"string\"]},{\"name\":\"id\",\"type\":\"string\"}],\"name\":\"DatosSucursal\",\"namespace\":\"Integracion.Esquemas.Referencias\",\"type\":\"record\"}]},{\"default\":null,\"name\":\"LogisticShipmentType\",\"type\":[\"null\",\"string\"]}],\"name\":\"Traza\",\"namespace\":\"Integracion.Esquemas\",\"type\":\"record\"}}],\"name\":\"Integracion.Esquemas.Trazas.EnvioSaleReacondicionamiento\",\"type\":\"record\"}"
}

func (r EnvioSaleReacondicionamiento) SchemaName() string {
	return "Integracion.Esquemas.Trazas.EnvioSaleReacondicionamiento"
}

func (_ EnvioSaleReacondicionamiento) SetBoolean(v bool)    { panic("Unsupported operation") }
func (_ EnvioSaleReacondicionamiento) SetInt(v int32)       { panic("Unsupported operation") }
func (_ EnvioSaleReacondicionamiento) SetLong(v int64)      { panic("Unsupported operation") }
func (_ EnvioSaleReacondicionamiento) SetFloat(v float32)   { panic("Unsupported operation") }
func (_ EnvioSaleReacondicionamiento) SetDouble(v float64)  { panic("Unsupported operation") }
func (_ EnvioSaleReacondicionamiento) SetBytes(v []byte)    { panic("Unsupported operation") }
func (_ EnvioSaleReacondicionamiento) SetString(v string)   { panic("Unsupported operation") }
func (_ EnvioSaleReacondicionamiento) SetUnionElem(v int64) { panic("Unsupported operation") }

func (r *EnvioSaleReacondicionamiento) Get(i int) types.Field {
	switch i {
	case 0:
		r.Traza = NewTraza()

		w := types.Record{Target: &r.Traza}

		return w

	}
	panic("Unknown field index")
}

func (r *EnvioSaleReacondicionamiento) SetDefault(i int) {
	switch i {
	}
	panic("Unknown field index")
}

func (r *EnvioSaleReacondicionamiento) NullField(i int) {
	switch i {
	}
	panic("Not a nullable field index")
}

func (_ EnvioSaleReacondicionamiento) AppendMap(key string) types.Field {
	panic("Unsupported operation")
}
func (_ EnvioSaleReacondicionamiento) AppendArray() types.Field { panic("Unsupported operation") }
func (_ EnvioSaleReacondicionamiento) HintSize(int)             { panic("Unsupported operation") }
func (_ EnvioSaleReacondicionamiento) Finalize()                {}

func (_ EnvioSaleReacondicionamiento) AvroCRC64Fingerprint() []byte {
	return []byte(EnvioSaleReacondicionamientoAvroCRC64Fingerprint)
}

func (r EnvioSaleReacondicionamiento) MarshalJSON() ([]byte, error) {
	var err error
	output := make(map[string]json.RawMessage)
	output["traza"], err = json.Marshal(r.Traza)
	if err != nil {
		return nil, err
	}
	return json.Marshal(output)
}

func (r *EnvioSaleReacondicionamiento) UnmarshalJSON(data []byte) error {
	var fields map[string]json.RawMessage
	if err := json.Unmarshal(data, &fields); err != nil {
		return err
	}

	var val json.RawMessage
	val = func() json.RawMessage {
		if v, ok := fields["traza"]; ok {
			return v
		}
		return nil
	}()

	if val != nil {
		if err := json.Unmarshal([]byte(val), &r.Traza); err != nil {
			return err
		}
	} else {
		return fmt.Errorf("no value specified for traza")
	}
	return nil
}
