// Code generated by github.com/actgardner/gogen-avro/v10. DO NOT EDIT.
/*
 * SOURCE:
 *     EnvioRemitenteSolicitaEstacionar.avsc
 */
package TrazasEvents

import (
	"encoding/json"
	"fmt"
	"io"

	"github.com/actgardner/gogen-avro/v10/compiler"
	"github.com/actgardner/gogen-avro/v10/vm"
	"github.com/actgardner/gogen-avro/v10/vm/types"
)

var _ = fmt.Printf

type EnvioRemitenteSolicitaEstacionar struct {
	Traza Traza `json:"traza"`
}

const EnvioRemitenteSolicitaEstacionarAvroCRC64Fingerprint = "\x1b\x90\x82=R\x0e?\x9f"

func NewEnvioRemitenteSolicitaEstacionar() EnvioRemitenteSolicitaEstacionar {
	r := EnvioRemitenteSolicitaEstacionar{}
	r.Traza = NewTraza()

	return r
}

func DeserializeEnvioRemitenteSolicitaEstacionar(r io.Reader) (EnvioRemitenteSolicitaEstacionar, error) {
	t := NewEnvioRemitenteSolicitaEstacionar()
	deser, err := compiler.CompileSchemaBytes([]byte(t.Schema()), []byte(t.Schema()))
	if err != nil {
		return t, err
	}

	err = vm.Eval(r, deser, &t)
	return t, err
}

func DeserializeEnvioRemitenteSolicitaEstacionarFromSchema(r io.Reader, schema string) (EnvioRemitenteSolicitaEstacionar, error) {
	t := NewEnvioRemitenteSolicitaEstacionar()

	deser, err := compiler.CompileSchemaBytes([]byte(schema), []byte(t.Schema()))
	if err != nil {
		return t, err
	}

	err = vm.Eval(r, deser, &t)
	return t, err
}

func writeEnvioRemitenteSolicitaEstacionar(r EnvioRemitenteSolicitaEstacionar, w io.Writer) error {
	var err error
	err = writeTraza(r.Traza, w)
	if err != nil {
		return err
	}
	return err
}

func (r EnvioRemitenteSolicitaEstacionar) Serialize(w io.Writer) error {
	return writeEnvioRemitenteSolicitaEstacionar(r, w)
}

func (r EnvioRemitenteSolicitaEstacionar) Schema() string {
	return "{\"fields\":[{\"name\":\"traza\",\"type\":{\"fields\":[{\"name\":\"codigoDeEnvio\",\"type\":\"string\"},{\"default\":null,\"name\":\"nombre\",\"type\":[\"null\",\"string\"]},{\"name\":\"cuando\",\"type\":{\"logicalType\":\"timestamp-millis\",\"type\":\"long\"}},{\"name\":\"codigoDeContratoInterno\",\"type\":\"string\"},{\"default\":null,\"name\":\"codigoDeContrato\",\"type\":[\"null\",\"string\"]},{\"default\":null,\"name\":\"estadoDelEnvio\",\"type\":[\"null\",\"string\"]},{\"default\":null,\"name\":\"cicloDelEnvio\",\"type\":[\"null\",\"string\"]},{\"default\":null,\"name\":\"operador\",\"type\":[\"null\",\"string\"]},{\"default\":null,\"name\":\"estadoDeLaRendicion\",\"type\":[\"null\",\"string\"]},{\"default\":null,\"name\":\"comentario\",\"type\":[\"null\",\"string\"]},{\"default\":null,\"name\":\"sucursalAsociadaAlEvento\",\"type\":[\"null\",{\"fields\":[{\"name\":\"codigo\",\"type\":\"string\"},{\"default\":null,\"name\":\"nombre\",\"type\":[\"null\",\"string\"]},{\"name\":\"id\",\"type\":\"string\"}],\"name\":\"DatosSucursal\",\"namespace\":\"Integracion.Esquemas.Referencias\",\"type\":\"record\"}]}],\"name\":\"Traza\",\"namespace\":\"Integracion.Esquemas\",\"type\":\"record\"}}],\"name\":\"Integracion.Esquemas.Trazas.EnvioRemitenteSolicitaEstacionar\",\"type\":\"record\"}"
}

func (r EnvioRemitenteSolicitaEstacionar) SchemaName() string {
	return "Integracion.Esquemas.Trazas.EnvioRemitenteSolicitaEstacionar"
}

func (_ EnvioRemitenteSolicitaEstacionar) SetBoolean(v bool)    { panic("Unsupported operation") }
func (_ EnvioRemitenteSolicitaEstacionar) SetInt(v int32)       { panic("Unsupported operation") }
func (_ EnvioRemitenteSolicitaEstacionar) SetLong(v int64)      { panic("Unsupported operation") }
func (_ EnvioRemitenteSolicitaEstacionar) SetFloat(v float32)   { panic("Unsupported operation") }
func (_ EnvioRemitenteSolicitaEstacionar) SetDouble(v float64)  { panic("Unsupported operation") }
func (_ EnvioRemitenteSolicitaEstacionar) SetBytes(v []byte)    { panic("Unsupported operation") }
func (_ EnvioRemitenteSolicitaEstacionar) SetString(v string)   { panic("Unsupported operation") }
func (_ EnvioRemitenteSolicitaEstacionar) SetUnionElem(v int64) { panic("Unsupported operation") }

func (r *EnvioRemitenteSolicitaEstacionar) Get(i int) types.Field {
	switch i {
	case 0:
		r.Traza = NewTraza()

		w := types.Record{Target: &r.Traza}

		return w

	}
	panic("Unknown field index")
}

func (r *EnvioRemitenteSolicitaEstacionar) SetDefault(i int) {
	switch i {
	}
	panic("Unknown field index")
}

func (r *EnvioRemitenteSolicitaEstacionar) NullField(i int) {
	switch i {
	}
	panic("Not a nullable field index")
}

func (_ EnvioRemitenteSolicitaEstacionar) AppendMap(key string) types.Field {
	panic("Unsupported operation")
}
func (_ EnvioRemitenteSolicitaEstacionar) AppendArray() types.Field { panic("Unsupported operation") }
func (_ EnvioRemitenteSolicitaEstacionar) HintSize(int)             { panic("Unsupported operation") }
func (_ EnvioRemitenteSolicitaEstacionar) Finalize()                {}

func (_ EnvioRemitenteSolicitaEstacionar) AvroCRC64Fingerprint() []byte {
	return []byte(EnvioRemitenteSolicitaEstacionarAvroCRC64Fingerprint)
}

func (r EnvioRemitenteSolicitaEstacionar) MarshalJSON() ([]byte, error) {
	var err error
	output := make(map[string]json.RawMessage)
	output["traza"], err = json.Marshal(r.Traza)
	if err != nil {
		return nil, err
	}
	return json.Marshal(output)
}

func (r *EnvioRemitenteSolicitaEstacionar) UnmarshalJSON(data []byte) error {
	var fields map[string]json.RawMessage
	if err := json.Unmarshal(data, &fields); err != nil {
		return err
	}

	var val json.RawMessage
	val = func() json.RawMessage {
		if v, ok := fields["traza"]; ok {
			return v
		}
		return nil
	}()

	if val != nil {
		if err := json.Unmarshal([]byte(val), &r.Traza); err != nil {
			return err
		}
	} else {
		return fmt.Errorf("no value specified for traza")
	}
	return nil
}
