// Code generated by github.com/actgardner/gogen-avro/v10. DO NOT EDIT.
/*
 * SOURCE:
 *     ExcedenteLogico.avsc
 */
package TrazasEvents

import (
	"encoding/json"
	"fmt"
	"io"

	"github.com/actgardner/gogen-avro/v10/compiler"
	"github.com/actgardner/gogen-avro/v10/vm"
	"github.com/actgardner/gogen-avro/v10/vm/types"
)

var _ = fmt.Printf

type ExcedenteLogico struct {
	Traza Traza `json:"traza"`
}

const ExcedenteLogicoAvroCRC64Fingerprint = "f\x80l.L\t\xc2{"

func NewExcedenteLogico() ExcedenteLogico {
	r := ExcedenteLogico{}
	r.Traza = NewTraza()

	return r
}

func DeserializeExcedenteLogico(r io.Reader) (ExcedenteLogico, error) {
	t := NewExcedenteLogico()
	deser, err := compiler.CompileSchemaBytes([]byte(t.Schema()), []byte(t.Schema()))
	if err != nil {
		return t, err
	}

	err = vm.Eval(r, deser, &t)
	return t, err
}

func DeserializeExcedenteLogicoFromSchema(r io.Reader, schema string) (ExcedenteLogico, error) {
	t := NewExcedenteLogico()

	deser, err := compiler.CompileSchemaBytes([]byte(schema), []byte(t.Schema()))
	if err != nil {
		return t, err
	}

	err = vm.Eval(r, deser, &t)
	return t, err
}

func writeExcedenteLogico(r ExcedenteLogico, w io.Writer) error {
	var err error
	err = writeTraza(r.Traza, w)
	if err != nil {
		return err
	}
	return err
}

func (r ExcedenteLogico) Serialize(w io.Writer) error {
	return writeExcedenteLogico(r, w)
}

func (r ExcedenteLogico) Schema() string {
	return "{\"fields\":[{\"name\":\"traza\",\"type\":{\"fields\":[{\"name\":\"codigoDeEnvio\",\"type\":\"string\"},{\"default\":null,\"name\":\"nombre\",\"type\":[\"null\",\"string\"]},{\"name\":\"cuando\",\"type\":{\"logicalType\":\"timestamp-millis\",\"type\":\"long\"}},{\"name\":\"codigoDeContratoInterno\",\"type\":\"string\"},{\"default\":null,\"name\":\"estadoDelEnvio\",\"type\":[\"null\",\"string\"]},{\"default\":null,\"name\":\"cicloDelEnvio\",\"type\":[\"null\",\"string\"]},{\"default\":null,\"name\":\"operador\",\"type\":[\"null\",\"string\"]},{\"default\":null,\"name\":\"estadoDeLaRendicion\",\"type\":[\"null\",\"string\"]},{\"default\":null,\"name\":\"comentario\",\"type\":[\"null\",\"string\"]},{\"default\":null,\"name\":\"sucursalAsociadaAlEvento\",\"type\":[\"null\",{\"fields\":[{\"name\":\"codigo\",\"type\":\"string\"},{\"default\":null,\"name\":\"nombre\",\"type\":[\"null\",\"string\"]},{\"name\":\"id\",\"type\":\"string\"}],\"name\":\"DatosSucursal\",\"namespace\":\"Integracion.Esquemas.Referencias\",\"type\":\"record\"}]}],\"name\":\"Traza\",\"namespace\":\"Integracion.Esquemas\",\"type\":\"record\"}}],\"name\":\"Integracion.Esquemas.Trazas.ExcedenteLogico\",\"type\":\"record\"}"
}

func (r ExcedenteLogico) SchemaName() string {
	return "Integracion.Esquemas.Trazas.ExcedenteLogico"
}

func (_ ExcedenteLogico) SetBoolean(v bool)    { panic("Unsupported operation") }
func (_ ExcedenteLogico) SetInt(v int32)       { panic("Unsupported operation") }
func (_ ExcedenteLogico) SetLong(v int64)      { panic("Unsupported operation") }
func (_ ExcedenteLogico) SetFloat(v float32)   { panic("Unsupported operation") }
func (_ ExcedenteLogico) SetDouble(v float64)  { panic("Unsupported operation") }
func (_ ExcedenteLogico) SetBytes(v []byte)    { panic("Unsupported operation") }
func (_ ExcedenteLogico) SetString(v string)   { panic("Unsupported operation") }
func (_ ExcedenteLogico) SetUnionElem(v int64) { panic("Unsupported operation") }

func (r *ExcedenteLogico) Get(i int) types.Field {
	switch i {
	case 0:
		r.Traza = NewTraza()

		w := types.Record{Target: &r.Traza}

		return w

	}
	panic("Unknown field index")
}

func (r *ExcedenteLogico) SetDefault(i int) {
	switch i {
	}
	panic("Unknown field index")
}

func (r *ExcedenteLogico) NullField(i int) {
	switch i {
	}
	panic("Not a nullable field index")
}

func (_ ExcedenteLogico) AppendMap(key string) types.Field { panic("Unsupported operation") }
func (_ ExcedenteLogico) AppendArray() types.Field         { panic("Unsupported operation") }
func (_ ExcedenteLogico) HintSize(int)                     { panic("Unsupported operation") }
func (_ ExcedenteLogico) Finalize()                        {}

func (_ ExcedenteLogico) AvroCRC64Fingerprint() []byte {
	return []byte(ExcedenteLogicoAvroCRC64Fingerprint)
}

func (r ExcedenteLogico) MarshalJSON() ([]byte, error) {
	var err error
	output := make(map[string]json.RawMessage)
	output["traza"], err = json.Marshal(r.Traza)
	if err != nil {
		return nil, err
	}
	return json.Marshal(output)
}

func (r *ExcedenteLogico) UnmarshalJSON(data []byte) error {
	var fields map[string]json.RawMessage
	if err := json.Unmarshal(data, &fields); err != nil {
		return err
	}

	var val json.RawMessage
	val = func() json.RawMessage {
		if v, ok := fields["traza"]; ok {
			return v
		}
		return nil
	}()

	if val != nil {
		if err := json.Unmarshal([]byte(val), &r.Traza); err != nil {
			return err
		}
	} else {
		return fmt.Errorf("no value specified for traza")
	}
	return nil
}
