// Code generated by github.com/actgardner/gogen-avro/v10. DO NOT EDIT.
/*
 * SOURCE:
 *     FaltanBultos.avsc
 */
package TrazasEvents

import (
	"encoding/json"
	"fmt"
	"io"

	"github.com/actgardner/gogen-avro/v10/compiler"
	"github.com/actgardner/gogen-avro/v10/vm"
	"github.com/actgardner/gogen-avro/v10/vm/types"
)

var _ = fmt.Printf

type FaltanBultos struct {
	Traza Traza `json:"traza"`
}

const FaltanBultosAvroCRC64Fingerprint = "\xc1\xf8\xf0\xa6\xb0R\x95\x82"

func NewFaltanBultos() FaltanBultos {
	r := FaltanBultos{}
	r.Traza = NewTraza()

	return r
}

func DeserializeFaltanBultos(r io.Reader) (FaltanBultos, error) {
	t := NewFaltanBultos()
	deser, err := compiler.CompileSchemaBytes([]byte(t.Schema()), []byte(t.Schema()))
	if err != nil {
		return t, err
	}

	err = vm.Eval(r, deser, &t)
	return t, err
}

func DeserializeFaltanBultosFromSchema(r io.Reader, schema string) (FaltanBultos, error) {
	t := NewFaltanBultos()

	deser, err := compiler.CompileSchemaBytes([]byte(schema), []byte(t.Schema()))
	if err != nil {
		return t, err
	}

	err = vm.Eval(r, deser, &t)
	return t, err
}

func writeFaltanBultos(r FaltanBultos, w io.Writer) error {
	var err error
	err = writeTraza(r.Traza, w)
	if err != nil {
		return err
	}
	return err
}

func (r FaltanBultos) Serialize(w io.Writer) error {
	return writeFaltanBultos(r, w)
}

func (r FaltanBultos) Schema() string {
	return "{\"fields\":[{\"name\":\"traza\",\"type\":{\"fields\":[{\"name\":\"codigoDeEnvio\",\"type\":\"string\"},{\"default\":null,\"name\":\"nombre\",\"type\":[\"null\",\"string\"]},{\"name\":\"cuando\",\"type\":{\"logicalType\":\"timestamp-millis\",\"type\":\"long\"}},{\"name\":\"codigoDeContratoInterno\",\"type\":\"string\"},{\"default\":null,\"name\":\"codigoDeContrato\",\"type\":[\"null\",\"string\"]},{\"default\":null,\"name\":\"estadoDelEnvio\",\"type\":[\"null\",\"string\"]},{\"default\":null,\"name\":\"cicloDelEnvio\",\"type\":[\"null\",\"string\"]},{\"default\":null,\"name\":\"operador\",\"type\":[\"null\",\"string\"]},{\"default\":null,\"name\":\"estadoDeLaRendicion\",\"type\":[\"null\",\"string\"]},{\"default\":null,\"name\":\"comentario\",\"type\":[\"null\",\"string\"]},{\"default\":null,\"name\":\"sucursalAsociadaAlEvento\",\"type\":[\"null\",{\"fields\":[{\"name\":\"codigo\",\"type\":\"string\"},{\"default\":null,\"name\":\"nombre\",\"type\":[\"null\",\"string\"]},{\"name\":\"id\",\"type\":\"string\"}],\"name\":\"DatosSucursal\",\"namespace\":\"Integracion.Esquemas.Referencias\",\"type\":\"record\"}]}],\"name\":\"Traza\",\"namespace\":\"Integracion.Esquemas\",\"type\":\"record\"}}],\"name\":\"Integracion.Esquemas.Trazas.FaltanBultos\",\"type\":\"record\"}"
}

func (r FaltanBultos) SchemaName() string {
	return "Integracion.Esquemas.Trazas.FaltanBultos"
}

func (_ FaltanBultos) SetBoolean(v bool)    { panic("Unsupported operation") }
func (_ FaltanBultos) SetInt(v int32)       { panic("Unsupported operation") }
func (_ FaltanBultos) SetLong(v int64)      { panic("Unsupported operation") }
func (_ FaltanBultos) SetFloat(v float32)   { panic("Unsupported operation") }
func (_ FaltanBultos) SetDouble(v float64)  { panic("Unsupported operation") }
func (_ FaltanBultos) SetBytes(v []byte)    { panic("Unsupported operation") }
func (_ FaltanBultos) SetString(v string)   { panic("Unsupported operation") }
func (_ FaltanBultos) SetUnionElem(v int64) { panic("Unsupported operation") }

func (r *FaltanBultos) Get(i int) types.Field {
	switch i {
	case 0:
		r.Traza = NewTraza()

		w := types.Record{Target: &r.Traza}

		return w

	}
	panic("Unknown field index")
}

func (r *FaltanBultos) SetDefault(i int) {
	switch i {
	}
	panic("Unknown field index")
}

func (r *FaltanBultos) NullField(i int) {
	switch i {
	}
	panic("Not a nullable field index")
}

func (_ FaltanBultos) AppendMap(key string) types.Field { panic("Unsupported operation") }
func (_ FaltanBultos) AppendArray() types.Field         { panic("Unsupported operation") }
func (_ FaltanBultos) HintSize(int)                     { panic("Unsupported operation") }
func (_ FaltanBultos) Finalize()                        {}

func (_ FaltanBultos) AvroCRC64Fingerprint() []byte {
	return []byte(FaltanBultosAvroCRC64Fingerprint)
}

func (r FaltanBultos) MarshalJSON() ([]byte, error) {
	var err error
	output := make(map[string]json.RawMessage)
	output["traza"], err = json.Marshal(r.Traza)
	if err != nil {
		return nil, err
	}
	return json.Marshal(output)
}

func (r *FaltanBultos) UnmarshalJSON(data []byte) error {
	var fields map[string]json.RawMessage
	if err := json.Unmarshal(data, &fields); err != nil {
		return err
	}

	var val json.RawMessage
	val = func() json.RawMessage {
		if v, ok := fields["traza"]; ok {
			return v
		}
		return nil
	}()

	if val != nil {
		if err := json.Unmarshal([]byte(val), &r.Traza); err != nil {
			return err
		}
	} else {
		return fmt.Errorf("no value specified for traza")
	}
	return nil
}
