// Code generated by github.com/actgardner/gogen-avro/v10. DO NOT EDIT.
/*
 * SOURCE:
 *     GeneracionArchivoAidaSolicitada.avsc
 */
package GloballpackEvents

import (
	"encoding/json"
	"fmt"
	"io"

	"github.com/actgardner/gogen-avro/v10/compiler"
	"github.com/actgardner/gogen-avro/v10/vm"
	"github.com/actgardner/gogen-avro/v10/vm/types"
)

var _ = fmt.Printf

type GeneracionArchivoAidaSolicitada struct {
	EventId string `json:"EventId"`

	SchemaVersion int32 `json:"SchemaVersion"`

	OccurredAtUtc int64 `json:"OccurredAtUtc"`

	CorrelationId string `json:"CorrelationId"`

	GuiaMadre string `json:"GuiaMadre"`

	IdManifiesto string `json:"IdManifiesto"`

	IdViaje string `json:"IdViaje"`

	SolicitadoPor SolicitanteGeneracionAida `json:"SolicitadoPor"`

	Origen string `json:"Origen"`
}

const GeneracionArchivoAidaSolicitadaAvroCRC64Fingerprint = "}Ѳ\xb5\xabx\xb4/"

func NewGeneracionArchivoAidaSolicitada() GeneracionArchivoAidaSolicitada {
	r := GeneracionArchivoAidaSolicitada{}
	r.SchemaVersion = 1
	r.SolicitadoPor = NewSolicitanteGeneracionAida()

	r.Origen = "backoffice"
	return r
}

func DeserializeGeneracionArchivoAidaSolicitada(r io.Reader) (GeneracionArchivoAidaSolicitada, error) {
	t := NewGeneracionArchivoAidaSolicitada()
	deser, err := compiler.CompileSchemaBytes([]byte(t.Schema()), []byte(t.Schema()))
	if err != nil {
		return t, err
	}

	err = vm.Eval(r, deser, &t)
	return t, err
}

func DeserializeGeneracionArchivoAidaSolicitadaFromSchema(r io.Reader, schema string) (GeneracionArchivoAidaSolicitada, error) {
	t := NewGeneracionArchivoAidaSolicitada()

	deser, err := compiler.CompileSchemaBytes([]byte(schema), []byte(t.Schema()))
	if err != nil {
		return t, err
	}

	err = vm.Eval(r, deser, &t)
	return t, err
}

func writeGeneracionArchivoAidaSolicitada(r GeneracionArchivoAidaSolicitada, w io.Writer) error {
	var err error
	err = vm.WriteString(r.EventId, w)
	if err != nil {
		return err
	}
	err = vm.WriteInt(r.SchemaVersion, w)
	if err != nil {
		return err
	}
	err = vm.WriteLong(r.OccurredAtUtc, w)
	if err != nil {
		return err
	}
	err = vm.WriteString(r.CorrelationId, w)
	if err != nil {
		return err
	}
	err = vm.WriteString(r.GuiaMadre, w)
	if err != nil {
		return err
	}
	err = vm.WriteString(r.IdManifiesto, w)
	if err != nil {
		return err
	}
	err = vm.WriteString(r.IdViaje, w)
	if err != nil {
		return err
	}
	err = writeSolicitanteGeneracionAida(r.SolicitadoPor, w)
	if err != nil {
		return err
	}
	err = vm.WriteString(r.Origen, w)
	if err != nil {
		return err
	}
	return err
}

func (r GeneracionArchivoAidaSolicitada) Serialize(w io.Writer) error {
	return writeGeneracionArchivoAidaSolicitada(r, w)
}

func (r GeneracionArchivoAidaSolicitada) Schema() string {
	return "{\"fields\":[{\"name\":\"EventId\",\"type\":\"string\"},{\"default\":1,\"name\":\"SchemaVersion\",\"type\":\"int\"},{\"name\":\"OccurredAtUtc\",\"type\":{\"logicalType\":\"timestamp-millis\",\"type\":\"long\"}},{\"name\":\"CorrelationId\",\"type\":\"string\"},{\"name\":\"GuiaMadre\",\"type\":\"string\"},{\"name\":\"IdManifiesto\",\"type\":\"string\"},{\"name\":\"IdViaje\",\"type\":\"string\"},{\"name\":\"SolicitadoPor\",\"type\":{\"fields\":[{\"name\":\"Id\",\"type\":\"string\"},{\"name\":\"Usuario\",\"type\":\"string\"}],\"name\":\"SolicitanteGeneracionAida\",\"type\":\"record\"}},{\"default\":\"backoffice\",\"name\":\"Origen\",\"type\":\"string\"}],\"name\":\"Andreani.Globallpack.Events.Record.GeneracionArchivoAidaSolicitada\",\"type\":\"record\"}"
}

func (r GeneracionArchivoAidaSolicitada) SchemaName() string {
	return "Andreani.Globallpack.Events.Record.GeneracionArchivoAidaSolicitada"
}

func (_ GeneracionArchivoAidaSolicitada) SetBoolean(v bool)    { panic("Unsupported operation") }
func (_ GeneracionArchivoAidaSolicitada) SetInt(v int32)       { panic("Unsupported operation") }
func (_ GeneracionArchivoAidaSolicitada) SetLong(v int64)      { panic("Unsupported operation") }
func (_ GeneracionArchivoAidaSolicitada) SetFloat(v float32)   { panic("Unsupported operation") }
func (_ GeneracionArchivoAidaSolicitada) SetDouble(v float64)  { panic("Unsupported operation") }
func (_ GeneracionArchivoAidaSolicitada) SetBytes(v []byte)    { panic("Unsupported operation") }
func (_ GeneracionArchivoAidaSolicitada) SetString(v string)   { panic("Unsupported operation") }
func (_ GeneracionArchivoAidaSolicitada) SetUnionElem(v int64) { panic("Unsupported operation") }

func (r *GeneracionArchivoAidaSolicitada) Get(i int) types.Field {
	switch i {
	case 0:
		w := types.String{Target: &r.EventId}

		return w

	case 1:
		w := types.Int{Target: &r.SchemaVersion}

		return w

	case 2:
		w := types.Long{Target: &r.OccurredAtUtc}

		return w

	case 3:
		w := types.String{Target: &r.CorrelationId}

		return w

	case 4:
		w := types.String{Target: &r.GuiaMadre}

		return w

	case 5:
		w := types.String{Target: &r.IdManifiesto}

		return w

	case 6:
		w := types.String{Target: &r.IdViaje}

		return w

	case 7:
		r.SolicitadoPor = NewSolicitanteGeneracionAida()

		w := types.Record{Target: &r.SolicitadoPor}

		return w

	case 8:
		w := types.String{Target: &r.Origen}

		return w

	}
	panic("Unknown field index")
}

func (r *GeneracionArchivoAidaSolicitada) SetDefault(i int) {
	switch i {
	case 1:
		r.SchemaVersion = 1
		return
	case 8:
		r.Origen = "backoffice"
		return
	}
	panic("Unknown field index")
}

func (r *GeneracionArchivoAidaSolicitada) NullField(i int) {
	switch i {
	}
	panic("Not a nullable field index")
}

func (_ GeneracionArchivoAidaSolicitada) AppendMap(key string) types.Field {
	panic("Unsupported operation")
}
func (_ GeneracionArchivoAidaSolicitada) AppendArray() types.Field { panic("Unsupported operation") }
func (_ GeneracionArchivoAidaSolicitada) HintSize(int)             { panic("Unsupported operation") }
func (_ GeneracionArchivoAidaSolicitada) Finalize()                {}

func (_ GeneracionArchivoAidaSolicitada) AvroCRC64Fingerprint() []byte {
	return []byte(GeneracionArchivoAidaSolicitadaAvroCRC64Fingerprint)
}

func (r GeneracionArchivoAidaSolicitada) MarshalJSON() ([]byte, error) {
	var err error
	output := make(map[string]json.RawMessage)
	output["EventId"], err = json.Marshal(r.EventId)
	if err != nil {
		return nil, err
	}
	output["SchemaVersion"], err = json.Marshal(r.SchemaVersion)
	if err != nil {
		return nil, err
	}
	output["OccurredAtUtc"], err = json.Marshal(r.OccurredAtUtc)
	if err != nil {
		return nil, err
	}
	output["CorrelationId"], err = json.Marshal(r.CorrelationId)
	if err != nil {
		return nil, err
	}
	output["GuiaMadre"], err = json.Marshal(r.GuiaMadre)
	if err != nil {
		return nil, err
	}
	output["IdManifiesto"], err = json.Marshal(r.IdManifiesto)
	if err != nil {
		return nil, err
	}
	output["IdViaje"], err = json.Marshal(r.IdViaje)
	if err != nil {
		return nil, err
	}
	output["SolicitadoPor"], err = json.Marshal(r.SolicitadoPor)
	if err != nil {
		return nil, err
	}
	output["Origen"], err = json.Marshal(r.Origen)
	if err != nil {
		return nil, err
	}
	return json.Marshal(output)
}

func (r *GeneracionArchivoAidaSolicitada) UnmarshalJSON(data []byte) error {
	var fields map[string]json.RawMessage
	if err := json.Unmarshal(data, &fields); err != nil {
		return err
	}

	var val json.RawMessage
	val = func() json.RawMessage {
		if v, ok := fields["EventId"]; ok {
			return v
		}
		return nil
	}()

	if val != nil {
		if err := json.Unmarshal([]byte(val), &r.EventId); err != nil {
			return err
		}
	} else {
		return fmt.Errorf("no value specified for EventId")
	}
	val = func() json.RawMessage {
		if v, ok := fields["SchemaVersion"]; ok {
			return v
		}
		return nil
	}()

	if val != nil {
		if err := json.Unmarshal([]byte(val), &r.SchemaVersion); err != nil {
			return err
		}
	} else {
		r.SchemaVersion = 1
	}
	val = func() json.RawMessage {
		if v, ok := fields["OccurredAtUtc"]; ok {
			return v
		}
		return nil
	}()

	if val != nil {
		if err := json.Unmarshal([]byte(val), &r.OccurredAtUtc); err != nil {
			return err
		}
	} else {
		return fmt.Errorf("no value specified for OccurredAtUtc")
	}
	val = func() json.RawMessage {
		if v, ok := fields["CorrelationId"]; ok {
			return v
		}
		return nil
	}()

	if val != nil {
		if err := json.Unmarshal([]byte(val), &r.CorrelationId); err != nil {
			return err
		}
	} else {
		return fmt.Errorf("no value specified for CorrelationId")
	}
	val = func() json.RawMessage {
		if v, ok := fields["GuiaMadre"]; ok {
			return v
		}
		return nil
	}()

	if val != nil {
		if err := json.Unmarshal([]byte(val), &r.GuiaMadre); err != nil {
			return err
		}
	} else {
		return fmt.Errorf("no value specified for GuiaMadre")
	}
	val = func() json.RawMessage {
		if v, ok := fields["IdManifiesto"]; ok {
			return v
		}
		return nil
	}()

	if val != nil {
		if err := json.Unmarshal([]byte(val), &r.IdManifiesto); err != nil {
			return err
		}
	} else {
		return fmt.Errorf("no value specified for IdManifiesto")
	}
	val = func() json.RawMessage {
		if v, ok := fields["IdViaje"]; ok {
			return v
		}
		return nil
	}()

	if val != nil {
		if err := json.Unmarshal([]byte(val), &r.IdViaje); err != nil {
			return err
		}
	} else {
		return fmt.Errorf("no value specified for IdViaje")
	}
	val = func() json.RawMessage {
		if v, ok := fields["SolicitadoPor"]; ok {
			return v
		}
		return nil
	}()

	if val != nil {
		if err := json.Unmarshal([]byte(val), &r.SolicitadoPor); err != nil {
			return err
		}
	} else {
		return fmt.Errorf("no value specified for SolicitadoPor")
	}
	val = func() json.RawMessage {
		if v, ok := fields["Origen"]; ok {
			return v
		}
		return nil
	}()

	if val != nil {
		if err := json.Unmarshal([]byte(val), &r.Origen); err != nil {
			return err
		}
	} else {
		r.Origen = "backoffice"
	}
	return nil
}
