// Code generated by github.com/actgardner/gogen-avro/v10. DO NOT EDIT.
/*
 * SOURCE:
 *     NotificacionEmail.avsc
 */
package GloballpackEvents

import (
	"encoding/json"
	"fmt"
	"io"

	"github.com/actgardner/gogen-avro/v10/compiler"
	"github.com/actgardner/gogen-avro/v10/vm"
	"github.com/actgardner/gogen-avro/v10/vm/types"
)

var _ = fmt.Printf

type NotificacionEmail struct {
	Email *UnionNullString `json:"Email"`

	Novedad *UnionNullString `json:"Novedad"`

	Body *UnionNullString `json:"Body"`
}

const NotificacionEmailAvroCRC64Fingerprint = "\xb3J\x1b\x96\xceFw\xa5"

func NewNotificacionEmail() NotificacionEmail {
	r := NotificacionEmail{}
	r.Email = nil
	r.Novedad = nil
	r.Body = nil
	return r
}

func DeserializeNotificacionEmail(r io.Reader) (NotificacionEmail, error) {
	t := NewNotificacionEmail()
	deser, err := compiler.CompileSchemaBytes([]byte(t.Schema()), []byte(t.Schema()))
	if err != nil {
		return t, err
	}

	err = vm.Eval(r, deser, &t)
	return t, err
}

func DeserializeNotificacionEmailFromSchema(r io.Reader, schema string) (NotificacionEmail, error) {
	t := NewNotificacionEmail()

	deser, err := compiler.CompileSchemaBytes([]byte(schema), []byte(t.Schema()))
	if err != nil {
		return t, err
	}

	err = vm.Eval(r, deser, &t)
	return t, err
}

func writeNotificacionEmail(r NotificacionEmail, w io.Writer) error {
	var err error
	err = writeUnionNullString(r.Email, w)
	if err != nil {
		return err
	}
	err = writeUnionNullString(r.Novedad, w)
	if err != nil {
		return err
	}
	err = writeUnionNullString(r.Body, w)
	if err != nil {
		return err
	}
	return err
}

func (r NotificacionEmail) Serialize(w io.Writer) error {
	return writeNotificacionEmail(r, w)
}

func (r NotificacionEmail) Schema() string {
	return "{\"fields\":[{\"default\":null,\"name\":\"Email\",\"type\":[\"null\",\"string\"]},{\"default\":null,\"name\":\"Novedad\",\"type\":[\"null\",\"string\"]},{\"default\":null,\"name\":\"Body\",\"type\":[\"null\",\"string\"]}],\"name\":\"Andreani.Globallpack.Events.Common.NotificacionEmail\",\"type\":\"record\"}"
}

func (r NotificacionEmail) SchemaName() string {
	return "Andreani.Globallpack.Events.Common.NotificacionEmail"
}

func (_ NotificacionEmail) SetBoolean(v bool)    { panic("Unsupported operation") }
func (_ NotificacionEmail) SetInt(v int32)       { panic("Unsupported operation") }
func (_ NotificacionEmail) SetLong(v int64)      { panic("Unsupported operation") }
func (_ NotificacionEmail) SetFloat(v float32)   { panic("Unsupported operation") }
func (_ NotificacionEmail) SetDouble(v float64)  { panic("Unsupported operation") }
func (_ NotificacionEmail) SetBytes(v []byte)    { panic("Unsupported operation") }
func (_ NotificacionEmail) SetString(v string)   { panic("Unsupported operation") }
func (_ NotificacionEmail) SetUnionElem(v int64) { panic("Unsupported operation") }

func (r *NotificacionEmail) Get(i int) types.Field {
	switch i {
	case 0:
		r.Email = NewUnionNullString()

		return r.Email
	case 1:
		r.Novedad = NewUnionNullString()

		return r.Novedad
	case 2:
		r.Body = NewUnionNullString()

		return r.Body
	}
	panic("Unknown field index")
}

func (r *NotificacionEmail) SetDefault(i int) {
	switch i {
	case 0:
		r.Email = nil
		return
	case 1:
		r.Novedad = nil
		return
	case 2:
		r.Body = nil
		return
	}
	panic("Unknown field index")
}

func (r *NotificacionEmail) NullField(i int) {
	switch i {
	case 0:
		r.Email = nil
		return
	case 1:
		r.Novedad = nil
		return
	case 2:
		r.Body = nil
		return
	}
	panic("Not a nullable field index")
}

func (_ NotificacionEmail) AppendMap(key string) types.Field { panic("Unsupported operation") }
func (_ NotificacionEmail) AppendArray() types.Field         { panic("Unsupported operation") }
func (_ NotificacionEmail) HintSize(int)                     { panic("Unsupported operation") }
func (_ NotificacionEmail) Finalize()                        {}

func (_ NotificacionEmail) AvroCRC64Fingerprint() []byte {
	return []byte(NotificacionEmailAvroCRC64Fingerprint)
}

func (r NotificacionEmail) MarshalJSON() ([]byte, error) {
	var err error
	output := make(map[string]json.RawMessage)
	output["Email"], err = json.Marshal(r.Email)
	if err != nil {
		return nil, err
	}
	output["Novedad"], err = json.Marshal(r.Novedad)
	if err != nil {
		return nil, err
	}
	output["Body"], err = json.Marshal(r.Body)
	if err != nil {
		return nil, err
	}
	return json.Marshal(output)
}

func (r *NotificacionEmail) UnmarshalJSON(data []byte) error {
	var fields map[string]json.RawMessage
	if err := json.Unmarshal(data, &fields); err != nil {
		return err
	}

	var val json.RawMessage
	val = func() json.RawMessage {
		if v, ok := fields["Email"]; ok {
			return v
		}
		return nil
	}()

	if val != nil {
		if err := json.Unmarshal([]byte(val), &r.Email); err != nil {
			return err
		}
	} else {
		r.Email = NewUnionNullString()

		r.Email = nil
	}
	val = func() json.RawMessage {
		if v, ok := fields["Novedad"]; ok {
			return v
		}
		return nil
	}()

	if val != nil {
		if err := json.Unmarshal([]byte(val), &r.Novedad); err != nil {
			return err
		}
	} else {
		r.Novedad = NewUnionNullString()

		r.Novedad = nil
	}
	val = func() json.RawMessage {
		if v, ok := fields["Body"]; ok {
			return v
		}
		return nil
	}()

	if val != nil {
		if err := json.Unmarshal([]byte(val), &r.Body); err != nil {
			return err
		}
	} else {
		r.Body = NewUnionNullString()

		r.Body = nil
	}
	return nil
}
