// Code generated by github.com/actgardner/gogen-avro/v10. DO NOT EDIT.
/*
 * SOURCE:
 *     RescateDevolucionRechazada.avsc
 */
package AccionesUnificadaEvents

import (
	"encoding/json"
	"fmt"
	"io"

	"github.com/actgardner/gogen-avro/v10/compiler"
	"github.com/actgardner/gogen-avro/v10/vm"
	"github.com/actgardner/gogen-avro/v10/vm/types"
)

var _ = fmt.Printf

type RescateDevolucionRechazada struct {
	MotivoDelRescateInterno *UnionNullString `json:"motivoDelRescateInterno"`

	Contrato string `json:"contrato"`

	NumeroDeSucursal string `json:"numeroDeSucursal"`

	CodigoCliente string `json:"codigoCliente"`

	NumeroAndreani []string `json:"numeroAndreani"`

	TipoDeRescate *UnionNullString `json:"tipoDeRescate"`

	Razon string `json:"razon"`
}

const RescateDevolucionRechazadaAvroCRC64Fingerprint = "\x95\xdbSH\x1d\xce{3"

func NewRescateDevolucionRechazada() RescateDevolucionRechazada {
	r := RescateDevolucionRechazada{}
	r.MotivoDelRescateInterno = nil
	r.NumeroAndreani = make([]string, 0)

	r.TipoDeRescate = nil
	return r
}

func DeserializeRescateDevolucionRechazada(r io.Reader) (RescateDevolucionRechazada, error) {
	t := NewRescateDevolucionRechazada()
	deser, err := compiler.CompileSchemaBytes([]byte(t.Schema()), []byte(t.Schema()))
	if err != nil {
		return t, err
	}

	err = vm.Eval(r, deser, &t)
	return t, err
}

func DeserializeRescateDevolucionRechazadaFromSchema(r io.Reader, schema string) (RescateDevolucionRechazada, error) {
	t := NewRescateDevolucionRechazada()

	deser, err := compiler.CompileSchemaBytes([]byte(schema), []byte(t.Schema()))
	if err != nil {
		return t, err
	}

	err = vm.Eval(r, deser, &t)
	return t, err
}

func writeRescateDevolucionRechazada(r RescateDevolucionRechazada, w io.Writer) error {
	var err error
	err = writeUnionNullString(r.MotivoDelRescateInterno, w)
	if err != nil {
		return err
	}
	err = vm.WriteString(r.Contrato, w)
	if err != nil {
		return err
	}
	err = vm.WriteString(r.NumeroDeSucursal, w)
	if err != nil {
		return err
	}
	err = vm.WriteString(r.CodigoCliente, w)
	if err != nil {
		return err
	}
	err = writeArrayString(r.NumeroAndreani, w)
	if err != nil {
		return err
	}
	err = writeUnionNullString(r.TipoDeRescate, w)
	if err != nil {
		return err
	}
	err = vm.WriteString(r.Razon, w)
	if err != nil {
		return err
	}
	return err
}

func (r RescateDevolucionRechazada) Serialize(w io.Writer) error {
	return writeRescateDevolucionRechazada(r, w)
}

func (r RescateDevolucionRechazada) Schema() string {
	return "{\"fields\":[{\"default\":null,\"name\":\"motivoDelRescateInterno\",\"type\":[\"null\",\"string\"]},{\"name\":\"contrato\",\"type\":\"string\"},{\"name\":\"numeroDeSucursal\",\"type\":\"string\"},{\"name\":\"codigoCliente\",\"type\":\"string\"},{\"name\":\"numeroAndreani\",\"type\":{\"items\":\"string\",\"type\":\"array\"}},{\"default\":null,\"name\":\"tipoDeRescate\",\"type\":[\"null\",\"string\"]},{\"name\":\"razon\",\"type\":\"string\"}],\"name\":\"Andreani.AccionesUnificada.Events.Record.RescateDevolucionRechazada\",\"type\":\"record\"}"
}

func (r RescateDevolucionRechazada) SchemaName() string {
	return "Andreani.AccionesUnificada.Events.Record.RescateDevolucionRechazada"
}

func (_ RescateDevolucionRechazada) SetBoolean(v bool)    { panic("Unsupported operation") }
func (_ RescateDevolucionRechazada) SetInt(v int32)       { panic("Unsupported operation") }
func (_ RescateDevolucionRechazada) SetLong(v int64)      { panic("Unsupported operation") }
func (_ RescateDevolucionRechazada) SetFloat(v float32)   { panic("Unsupported operation") }
func (_ RescateDevolucionRechazada) SetDouble(v float64)  { panic("Unsupported operation") }
func (_ RescateDevolucionRechazada) SetBytes(v []byte)    { panic("Unsupported operation") }
func (_ RescateDevolucionRechazada) SetString(v string)   { panic("Unsupported operation") }
func (_ RescateDevolucionRechazada) SetUnionElem(v int64) { panic("Unsupported operation") }

func (r *RescateDevolucionRechazada) Get(i int) types.Field {
	switch i {
	case 0:
		r.MotivoDelRescateInterno = NewUnionNullString()

		return r.MotivoDelRescateInterno
	case 1:
		w := types.String{Target: &r.Contrato}

		return w

	case 2:
		w := types.String{Target: &r.NumeroDeSucursal}

		return w

	case 3:
		w := types.String{Target: &r.CodigoCliente}

		return w

	case 4:
		r.NumeroAndreani = make([]string, 0)

		w := ArrayStringWrapper{Target: &r.NumeroAndreani}

		return w

	case 5:
		r.TipoDeRescate = NewUnionNullString()

		return r.TipoDeRescate
	case 6:
		w := types.String{Target: &r.Razon}

		return w

	}
	panic("Unknown field index")
}

func (r *RescateDevolucionRechazada) SetDefault(i int) {
	switch i {
	case 0:
		r.MotivoDelRescateInterno = nil
		return
	case 5:
		r.TipoDeRescate = nil
		return
	}
	panic("Unknown field index")
}

func (r *RescateDevolucionRechazada) NullField(i int) {
	switch i {
	case 0:
		r.MotivoDelRescateInterno = nil
		return
	case 5:
		r.TipoDeRescate = nil
		return
	}
	panic("Not a nullable field index")
}

func (_ RescateDevolucionRechazada) AppendMap(key string) types.Field { panic("Unsupported operation") }
func (_ RescateDevolucionRechazada) AppendArray() types.Field         { panic("Unsupported operation") }
func (_ RescateDevolucionRechazada) HintSize(int)                     { panic("Unsupported operation") }
func (_ RescateDevolucionRechazada) Finalize()                        {}

func (_ RescateDevolucionRechazada) AvroCRC64Fingerprint() []byte {
	return []byte(RescateDevolucionRechazadaAvroCRC64Fingerprint)
}

func (r RescateDevolucionRechazada) MarshalJSON() ([]byte, error) {
	var err error
	output := make(map[string]json.RawMessage)
	output["motivoDelRescateInterno"], err = json.Marshal(r.MotivoDelRescateInterno)
	if err != nil {
		return nil, err
	}
	output["contrato"], err = json.Marshal(r.Contrato)
	if err != nil {
		return nil, err
	}
	output["numeroDeSucursal"], err = json.Marshal(r.NumeroDeSucursal)
	if err != nil {
		return nil, err
	}
	output["codigoCliente"], err = json.Marshal(r.CodigoCliente)
	if err != nil {
		return nil, err
	}
	output["numeroAndreani"], err = json.Marshal(r.NumeroAndreani)
	if err != nil {
		return nil, err
	}
	output["tipoDeRescate"], err = json.Marshal(r.TipoDeRescate)
	if err != nil {
		return nil, err
	}
	output["razon"], err = json.Marshal(r.Razon)
	if err != nil {
		return nil, err
	}
	return json.Marshal(output)
}

func (r *RescateDevolucionRechazada) UnmarshalJSON(data []byte) error {
	var fields map[string]json.RawMessage
	if err := json.Unmarshal(data, &fields); err != nil {
		return err
	}

	var val json.RawMessage
	val = func() json.RawMessage {
		if v, ok := fields["motivoDelRescateInterno"]; ok {
			return v
		}
		return nil
	}()

	if val != nil {
		if err := json.Unmarshal([]byte(val), &r.MotivoDelRescateInterno); err != nil {
			return err
		}
	} else {
		r.MotivoDelRescateInterno = NewUnionNullString()

		r.MotivoDelRescateInterno = nil
	}
	val = func() json.RawMessage {
		if v, ok := fields["contrato"]; ok {
			return v
		}
		return nil
	}()

	if val != nil {
		if err := json.Unmarshal([]byte(val), &r.Contrato); err != nil {
			return err
		}
	} else {
		return fmt.Errorf("no value specified for contrato")
	}
	val = func() json.RawMessage {
		if v, ok := fields["numeroDeSucursal"]; ok {
			return v
		}
		return nil
	}()

	if val != nil {
		if err := json.Unmarshal([]byte(val), &r.NumeroDeSucursal); err != nil {
			return err
		}
	} else {
		return fmt.Errorf("no value specified for numeroDeSucursal")
	}
	val = func() json.RawMessage {
		if v, ok := fields["codigoCliente"]; ok {
			return v
		}
		return nil
	}()

	if val != nil {
		if err := json.Unmarshal([]byte(val), &r.CodigoCliente); err != nil {
			return err
		}
	} else {
		return fmt.Errorf("no value specified for codigoCliente")
	}
	val = func() json.RawMessage {
		if v, ok := fields["numeroAndreani"]; ok {
			return v
		}
		return nil
	}()

	if val != nil {
		if err := json.Unmarshal([]byte(val), &r.NumeroAndreani); err != nil {
			return err
		}
	} else {
		return fmt.Errorf("no value specified for numeroAndreani")
	}
	val = func() json.RawMessage {
		if v, ok := fields["tipoDeRescate"]; ok {
			return v
		}
		return nil
	}()

	if val != nil {
		if err := json.Unmarshal([]byte(val), &r.TipoDeRescate); err != nil {
			return err
		}
	} else {
		r.TipoDeRescate = NewUnionNullString()

		r.TipoDeRescate = nil
	}
	val = func() json.RawMessage {
		if v, ok := fields["razon"]; ok {
			return v
		}
		return nil
	}()

	if val != nil {
		if err := json.Unmarshal([]byte(val), &r.Razon); err != nil {
			return err
		}
	} else {
		return fmt.Errorf("no value specified for razon")
	}
	return nil
}
