// Code generated by github.com/actgardner/gogen-avro/v10. DO NOT EDIT.
/*
 * SOURCE:
 *     TransportistasDistribucionPosicion.avsc
 */
package ApiPositionEvents

import (
	"encoding/json"
	"fmt"
	"io"

	"github.com/actgardner/gogen-avro/v10/compiler"
	"github.com/actgardner/gogen-avro/v10/vm"
	"github.com/actgardner/gogen-avro/v10/vm/types"
)

var _ = fmt.Printf

type TransportistasDistribucionPosicion struct {
	Dni string `json:"Dni"`

	Fecha string `json:"Fecha"`

	Latitud string `json:"Latitud"`

	Longitud string `json:"Longitud"`
}

const TransportistasDistribucionPosicionAvroCRC64Fingerprint = "\xc086\xf8\t\xbe\x11\x80"

func NewTransportistasDistribucionPosicion() TransportistasDistribucionPosicion {
	r := TransportistasDistribucionPosicion{}
	return r
}

func DeserializeTransportistasDistribucionPosicion(r io.Reader) (TransportistasDistribucionPosicion, error) {
	t := NewTransportistasDistribucionPosicion()
	deser, err := compiler.CompileSchemaBytes([]byte(t.Schema()), []byte(t.Schema()))
	if err != nil {
		return t, err
	}

	err = vm.Eval(r, deser, &t)
	return t, err
}

func DeserializeTransportistasDistribucionPosicionFromSchema(r io.Reader, schema string) (TransportistasDistribucionPosicion, error) {
	t := NewTransportistasDistribucionPosicion()

	deser, err := compiler.CompileSchemaBytes([]byte(schema), []byte(t.Schema()))
	if err != nil {
		return t, err
	}

	err = vm.Eval(r, deser, &t)
	return t, err
}

func writeTransportistasDistribucionPosicion(r TransportistasDistribucionPosicion, w io.Writer) error {
	var err error
	err = vm.WriteString(r.Dni, w)
	if err != nil {
		return err
	}
	err = vm.WriteString(r.Fecha, w)
	if err != nil {
		return err
	}
	err = vm.WriteString(r.Latitud, w)
	if err != nil {
		return err
	}
	err = vm.WriteString(r.Longitud, w)
	if err != nil {
		return err
	}
	return err
}

func (r TransportistasDistribucionPosicion) Serialize(w io.Writer) error {
	return writeTransportistasDistribucionPosicion(r, w)
}

func (r TransportistasDistribucionPosicion) Schema() string {
	return "{\"fields\":[{\"name\":\"Dni\",\"type\":\"string\"},{\"name\":\"Fecha\",\"type\":\"string\"},{\"name\":\"Latitud\",\"type\":\"string\"},{\"name\":\"Longitud\",\"type\":\"string\"}],\"name\":\"Andreani.ApiPosition.Events.Record.TransportistasDistribucionPosicion\",\"type\":\"record\"}"
}

func (r TransportistasDistribucionPosicion) SchemaName() string {
	return "Andreani.ApiPosition.Events.Record.TransportistasDistribucionPosicion"
}

func (_ TransportistasDistribucionPosicion) SetBoolean(v bool)    { panic("Unsupported operation") }
func (_ TransportistasDistribucionPosicion) SetInt(v int32)       { panic("Unsupported operation") }
func (_ TransportistasDistribucionPosicion) SetLong(v int64)      { panic("Unsupported operation") }
func (_ TransportistasDistribucionPosicion) SetFloat(v float32)   { panic("Unsupported operation") }
func (_ TransportistasDistribucionPosicion) SetDouble(v float64)  { panic("Unsupported operation") }
func (_ TransportistasDistribucionPosicion) SetBytes(v []byte)    { panic("Unsupported operation") }
func (_ TransportistasDistribucionPosicion) SetString(v string)   { panic("Unsupported operation") }
func (_ TransportistasDistribucionPosicion) SetUnionElem(v int64) { panic("Unsupported operation") }

func (r *TransportistasDistribucionPosicion) Get(i int) types.Field {
	switch i {
	case 0:
		w := types.String{Target: &r.Dni}

		return w

	case 1:
		w := types.String{Target: &r.Fecha}

		return w

	case 2:
		w := types.String{Target: &r.Latitud}

		return w

	case 3:
		w := types.String{Target: &r.Longitud}

		return w

	}
	panic("Unknown field index")
}

func (r *TransportistasDistribucionPosicion) SetDefault(i int) {
	switch i {
	}
	panic("Unknown field index")
}

func (r *TransportistasDistribucionPosicion) NullField(i int) {
	switch i {
	}
	panic("Not a nullable field index")
}

func (_ TransportistasDistribucionPosicion) AppendMap(key string) types.Field {
	panic("Unsupported operation")
}
func (_ TransportistasDistribucionPosicion) AppendArray() types.Field { panic("Unsupported operation") }
func (_ TransportistasDistribucionPosicion) HintSize(int)             { panic("Unsupported operation") }
func (_ TransportistasDistribucionPosicion) Finalize()                {}

func (_ TransportistasDistribucionPosicion) AvroCRC64Fingerprint() []byte {
	return []byte(TransportistasDistribucionPosicionAvroCRC64Fingerprint)
}

func (r TransportistasDistribucionPosicion) MarshalJSON() ([]byte, error) {
	var err error
	output := make(map[string]json.RawMessage)
	output["Dni"], err = json.Marshal(r.Dni)
	if err != nil {
		return nil, err
	}
	output["Fecha"], err = json.Marshal(r.Fecha)
	if err != nil {
		return nil, err
	}
	output["Latitud"], err = json.Marshal(r.Latitud)
	if err != nil {
		return nil, err
	}
	output["Longitud"], err = json.Marshal(r.Longitud)
	if err != nil {
		return nil, err
	}
	return json.Marshal(output)
}

func (r *TransportistasDistribucionPosicion) UnmarshalJSON(data []byte) error {
	var fields map[string]json.RawMessage
	if err := json.Unmarshal(data, &fields); err != nil {
		return err
	}

	var val json.RawMessage
	val = func() json.RawMessage {
		if v, ok := fields["Dni"]; ok {
			return v
		}
		return nil
	}()

	if val != nil {
		if err := json.Unmarshal([]byte(val), &r.Dni); err != nil {
			return err
		}
	} else {
		return fmt.Errorf("no value specified for Dni")
	}
	val = func() json.RawMessage {
		if v, ok := fields["Fecha"]; ok {
			return v
		}
		return nil
	}()

	if val != nil {
		if err := json.Unmarshal([]byte(val), &r.Fecha); err != nil {
			return err
		}
	} else {
		return fmt.Errorf("no value specified for Fecha")
	}
	val = func() json.RawMessage {
		if v, ok := fields["Latitud"]; ok {
			return v
		}
		return nil
	}()

	if val != nil {
		if err := json.Unmarshal([]byte(val), &r.Latitud); err != nil {
			return err
		}
	} else {
		return fmt.Errorf("no value specified for Latitud")
	}
	val = func() json.RawMessage {
		if v, ok := fields["Longitud"]; ok {
			return v
		}
		return nil
	}()

	if val != nil {
		if err := json.Unmarshal([]byte(val), &r.Longitud); err != nil {
			return err
		}
	} else {
		return fmt.Errorf("no value specified for Longitud")
	}
	return nil
}
