name: Create/update tag
on:
  push:
    branches: ["main"]
jobs:
  create-tag:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: rickstaa/action-create-tag@v1
        with:
          tag: "v1.1.$GITHUB_RUN_NUMBER"
          message: "Latest release"
